### ISSUE TITLE
Give moderators access to the /skull command

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#100]
Currently the /skull command is used on Survival to place player heads on the clan wall in spawn, as well as to replace griefed player heads elsewhere on the map.

Giving moderators access to the /skull command (it is currently admin-only) will release a great amount of modreqs from the admin-only group, which means easier and faster moderation in general.

**Comment by LadyCailin** [comment]
Added, though untested, can someone verify for me? Thanks ^_^

**Comment by tompreuss** [comment]
Adding note that this was tested by myself and Cailin on S.
