### ISSUE TITLE
Correct permissions issue(s) with the ModReq system

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#101]
An issue that has apparently been in effect since the start of the current Survival revision (April 6th), moderators are not able to /elevate or /done modreqs outside of ModMode. Similar to the recent issues involving not being able to see the incoming of new modreqs and being unable to see the closing of modreqs handled by other staff members, I believe this is potentially affecting only the Survival server.

Whilst not a huge issue, I understand this is another example of the ongoing permissions issues we seem to be having, so it's part of a bigger problem. It would be incredibly beneficial if we could get this fixed, as it is unnecessary to go into ModMode simply to /elevate a modreq or close one that does not require going into ModMode at all. I understand these issues only exist for commands pertaining to the ModReq system, as commands such as /trace, /mute, and /kick all work fine outside of ModMode.

**Comment by totemo** [comment]
Looking at the current configuration, moderators appear to have been given all of the requisite permission nodes, sometimes more than once.  I'm going to put the blame on bPermission.

I will try to normalise the survival configuration to be more like that of PVE.  It's showing signs of attempts to fix this by brute force.

**Comment by totemo** [comment]
Ok, so apparently /done was working but not /elevate.  I've rationalised the permission modes and had a couple of moderators re-test everything in and out of ModMode.  Closing as fixed.
