### ISSUE TITLE
Add aliases to list all regions to all servers

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#102]
basically just add this somewhere to commandhelper files

*:/regions-here [$] = msg( concat( color(~admin prerogative~), 'Regions located here:', array_implode( sk_regions_at( ploc( player() ) ), ', ' ) ) )
*:/regions-there [$] = msg( concat( color(~admin prerogative~), 'Regions located there:', array_implode( sk_regions_at( pcursor( player() ) ), ', ' ) ) )

The first would list all regions the player is standing in, the second would do what a wood sword does, without needing to be crafted

**Comment by LadyCailin** [comment]
Added!

**Comment by LadyCailin** [comment]
Lude, can you make a note of this somewhere in the wiki, wherever it's appropriate?

**Comment by mattman00000** [comment]
so uh, what does "Added!" mean in this context? it does not appear to be added yet, at least not in a way that does anything other than send "Unknown command" to my client :/

**Comment by LadyCailin** [comment]
Oh... what server?

**Comment by mattman00000** [comment]
pve

**Comment by ludeman84** [comment]
LadyCailin/mattman00000, let me know once the commands are working and I'll get them on the list of commands wiki page.

**Comment by LadyCailin** [comment]
mmk, should be on there now.

**Comment by ghost** [comment]
Ok so what command is this and what exactly does it do?

**Comment by zifnab06** [comment]
@Diznatch52:

/regions-here: prints a list of regions at the current player's location
/regions-there: prints a list of regions at the first block in front of the player's crosshair

**Comment by totemo** [comment]
Closing. Was implemented some time ago. Now available everywhere.
