### ISSUE TITLE
Breaking lever attached to top of /cprivate dropper deregisters the dropper on P

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#104]
Title says it all

**Comment by FourDown** [comment]
Is this still an issue @mattman00000 ?

**Comment by zifnab06** [comment]
I just tested this on P, it appears to be fixed. 

(Placed dropper, attached lever to top of dropper, broke lever, dropper is still protected. Also attempted placing switch on wall behind dropper, dropper is still protected)
