### ISSUE TITLE
Make death messages able to be toggled by admins (by region if possible, at least globally)

### ISSUE THREAD

**Issue by Denevien** [NerdNu/NerdBugs#105]
To many times (like the "5K" at PvE spawn), there is something that spams chat with death messages. Another would be wither fight arenas. If it was possible to turn death messages off in certain regions, that would be great. Worst case, it would be great to be able to have the option to turn it off globally via and ingame command for admins.

**Comment by LadyCailin** [comment]
Done. /toggle-death-messages toggles it. Admin only.
