### ISSUE TITLE
[Clanchat] Blank line when changing channels

### ISSUE THREAD

**Issue by zifnab06** [NerdNu/NerdBugs#106]
Typing /c [channel] posts and empty line to [channel]

The same logic behind typing '/c' with no arguments should be able to fix this (except without displaying an error message)

**Comment by mattman00000** [comment]
I at least want it to switch default channel

**Comment by zifnab06** [comment]
So:

/c #p80 (Changes default channel to #p80, and outputs the "Your default channel has been changed to #p80 message)

AND

/c #p80 Hello! (Changes default channel to #p80 and sends Hello! to #p80, as well as displaying "Your default channel has been changed to #p80)

(Sorry, its finals week. I haven't been sleeping much. If this doesn't make sense, please disreguard it)

**Comment by LadyCailin** [comment]
Fixed.
