### ISSUE TITLE
Right clicking with ender pearl when a block is highlighted does nothing on P

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#107]
Just what the title says...

**Comment by Tharine** [comment]
Confirmed as an issue on Survival as well. Trying to right click anything with a hitbox (regardless of whether it is a 'transparent' block or not) will cause no action to occur. Aiming and right clicking at players and into the far distance work as intended. This became apparent a couple of days before we updated to 1.5.2, so this is unlikely to be an issue on Mojang's side of things, and is possibly an unintended effect of some other change recently made.

**Comment by mattman00000** [comment]
Recently, NoCheatPlus was removed from PvE, and with it, this issue disappeared. Could be a glitch/feature of NCP.

**Comment by Tharine** [comment]
I understand from speaking with another server owner that it is indeed a feature of the most (or one of the more) recent update(s) of NCP, which is indeed why it isn't in effect now that NCP has been taken off of PvE. To avoid opening another issue, I would like to have this one kept open until the feature is disabled for Survival, as we did not approve of it being enabled (we were not aware that such a change would be in store).

**Comment by LadyCailin** [comment]
Fixed. It was a NC configuration issue.
