### ISSUE TITLE
BROWN is not a supported color for clanchat

### ISSUE THREAD

**Issue by zifnab06** [NerdNu/NerdBugs#108]
if BROWN is a supported color in CommandHelper, i'd like to request that it is added to ClanChat. 

Patch:

change line 72 of auto_include.msa to:

```
            BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, BROWN)
```

**Comment by LadyCailin** [comment]
That's not even a supported color in Minecraft at all. Can't do anything about that, sorry!
