### ISSUE TITLE
Add arguments to /nearest-place

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#110]
I would suggest that arguments for /nearest-place be added so that someone can find the nearest place to given coords that someone may or may not be currently at.

**Comment by FourDown** [comment]
Unfortunately, the stuff for this isn't on GitHub, so I can't do this. 

If it gets uploaded, I'll give it a go.

**Comment by totemo** [comment]
You're up:

https://github.com/NerdNu/nerdCH/blob/master/LocalPackages/pve-only/place.msa

**Comment by totemo** [comment]
Very well done. Merged and tested on PVE.
