### ISSUE TITLE
Armoured head drops no longer work at all

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#112]
Tested quite extensively on Survival, the setup we have that manages player head drops from armoured kills no longer works. I tried to look into this when the problem first started happening, and for some time perspective (and possibly (?) some explanation for the change) it seemed to have come into effect a few hours after this change was made to CH itself: https://github.com/sk89q/commandhelper/pull/123

As well as receiving no head drops, the decapitation message doesn't display either, so it seems to be a problem with the setup as a whole. Hopefully this isn't a complicated fix :)

**Comment by FourDown** [comment]
Sent a message to LadyCailin about this on IRC, hopefully this gets fixed asap.

Also, I hope the issues in this report get fixed too:
https://github.com/NerdNu/NerdBugs/issues/94

**Comment by LadyCailin** [comment]
Fixed ^_^
