### ISSUE TITLE
Issues surrounding planned server restarts

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#113]
Something that i've noticed has been happening for some time on and off for both Survival and PvE (cannot verify for Creative, as I don't visit there often enough to notice), either of the servers will have their planned restart, go down, and not come back up again until the next one, two hours later.

It's obviously not the most immediate of issues, but i've attempted contact with the tech admins several times about this to no response, so i'm hoping submitting this issue here will get some traction. Given the timing of when this started, and that it involves server restarts, I had wondered if it were an issue with the mark2 wrapper, and I spoke with a friend who is more familiar with it than I, their response being:

"(...) So I'd assume it's a config option or something is breaking during the restart which is causing it to halt, then get picked up next start. Perhaps not shutting down and cleaning fast enough?"

Hopefully that helps to give some insight into where the issue is located, so that something that can be done to get it mended. I haven't witnessed this occurring in the last week, but i've also not been playing anywhere near as often as I used to, so I can't speak for whether it's been resolved or not by now. Either way, I would really appreciate hearing an explanation for the cause of this if/when it does get fixed.

**Comment by barneygale** [comment]
Sounds mark2-related. Myself an edk are usually available in #mark2 on freenode, or #llama on gamesurge. Always a pleasure to help you folks with tech things where needed!

**Comment by gsand** [comment]
it might be a misconfigured script.txt, that doesnt happen ever on any of my mark2 installs.

**Comment by totemo** [comment]
I'll have a look into it.  Perhaps the backup is taking longer than expected.

Also, we are due to upgrade to a later version of mark2 to fix other issues.  I'll hold back on this issue until after that.

**Comment by totemo** [comment]
During the most recent hang on start up, on PvE, MCBouncer prints its startup message and then the CPU stays pegged at 200%.  So either in there or something happening in WorldEdit, which is the next plugin in the sequence.

2013-07-13 06:16:14 [INFO] [MCBouncer] Enabling MCBouncer v1.3.1beta
2013-07-13 06:16:42 [INFO] Read timed out
2013-07-13 06:16:43 [INFO] Read timed out
2013-07-13 06:16:47 [INFO] Read timed out
2013-07-13 06:16:49 [INFO] Read timed out
2013-07-13 06:16:52 [INFO] Read timed out

**Comment by totemo** [comment]
I haven't seen this in some time.  We are on a later version of mark2 and everything for that matter.  We'll reopen the issue if or when it recurs.
