### ISSUE TITLE
Add new types to Easy Signs

### ISSUE THREAD

**Issue by Denevien** [NerdNu/NerdBugs#116]
Two new types need to be added to the easy signs.

1) ci : This would have no arguments, and would clear inventory of the player.

2) give : This would have two arguments, one for quantity, one for block type.

**Comment by LadyCailin** [comment]
I think I'm going to allow for multiple sign types to be applied to any sign, and you'll be able to set as many actions as you want, so each of these will be different types (and can even be applied multiple times with different arguments)

**Comment by Denevien** [comment]
Awesome. I'd like to add another. Can we get equip with multiple arguments: first what is equipped and second what slot. Ideally, this could be used to put wool on players heads, or let them "suit up" in their evening formal diamond armor.

**Comment by LadyCailin** [comment]
Done. Check the docs for usage.
