### ISSUE TITLE
Survival mods (in ModMode) unable to check regions

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#118]
Another permissions issue it seems, Survival moderators cannot use the wooden sword or command /region info to check a region whilst in ModMode. Using /region info outside of a region returns the appropriate "No region ID specified and no region found at current location"  but attempting it whilst within an actual region returns a permissions error.

Would really appreciate a thorough look into these permissions issues we've been having on Survival, this seems to be one of the major ongoing issues we continue to have as a server and it's affecting our staffing capabilities in so many ways.

**Comment by totemo** [comment]
Added:
    - worldguard.region.info
    - worldguard.region.info.member
    - worldguard.region.info.own
    - worldguard.region.select.*
    - worldguard.region.wand

to ModMode permissions. Tested with moderator in ModMode. Fixed.
