### ISSUE TITLE
Write a chat plugin

### ISSUE THREAD

**Issue by Deaygo** [NerdNu/NerdBugs#12]
for things like
- `/me`
- `/msg`
- `/r`
- `/mute` and `/unmute`

when using `/r` make sure that it logs who the message is actually going to.

**Comment by stevommmm** [comment]
Mute and unmute are currently being done by lolno iirc, the rest would be commandhelper

**Comment by barneygale** [comment]
Not sure why we need this. /me is straightforward in CH, and /msg and /r are already written and pretty versitile. Adding logging for messaging is easy - I can do that now if you'd like?

**Comment by stevommmm** [comment]
I would say do that and we can resolve this, the current setup functions fine.
