### ISSUE TITLE
Implement multiple enchantments and slot looping for /enchant command

### ISSUE THREAD

**Issue by GMMan** [NerdNu/NerdBugs#120]
It would be really helpful if multiple enchantments can be applied at once, and also for a range of slots to be selected to enchant at the same time. Currently, for digs, I need to enchant each (stack of) golden tools with two enchantments, doing it for each stack in my hotbar. That's 18 commands I have to send, and the server always complains about me spamming. If I can enter one command to replace those 18, that would save considerable time.

**Comment by LadyCailin** [comment]
I don't think we're really interested in taking the time to add this, since it would benefit so few people. Thanks for the suggestion though!
