### ISSUE TITLE
Give players ability to see who owns particular pets

### ISSUE THREAD

**Issue by buzzie71** [NerdNu/NerdBugs#123]
I've seen a few modreqs and complaints of pets being obnoxiously loud in public places, and with no way of finding out who owns said pets, it's difficult to act effectively as staff.  If the player who owns the pets in question is, for example, inactive, perhaps it would be possible to move them into storage and return them on request; if the owner is active, however, it would probably be more preferable for player contact to take place first (similar to build move/removals, where attempt at contact must happen first).

Certainly the server knows who owns which pets, but is it possible for someone to extract that information from the server in text form after some sort of command (say, /findowner)?

**Comment by LadyCailin** [comment]
This is a good idea. I'll look into what it will take to add this.

**Comment by tompreuss** [comment]
Looks like it can be done with [interface org.bukkit.entity.Tameable getOwner()](http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/Tameable.html#getOwner(\)).

Additionally, if we could add the ability for assigning owners to spawned pets (done when replacing griefed pets) that would save a big hassle over the current method.  This appears possible with [setTamed()](http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/Tameable.html#setTamed(boolean\)).

**Comment by buzzie71** [comment]
EDIT:

Decided to give plugin writing a try a few days ago, ended up implementing a way for players to see the owners of tamed animals they right-click on as part of a few funsies things I'm starting off with :P.  I'll take a shot at spawning of already tamed animals as tompreuss mentioned above.

**Comment by gsand** [comment]
This can be done easily with a simple 3-line commandhelper script.

**Comment by buzzie71** [comment]
I offer my code up for potential use - among the not-so-much-stuff in there, players will get a message stating who a pet's owner is if they right-click one, and /spawn-tame-mob will spawn a tamed ocelot/wolf at the command runner's feet tamed to a specified player: 
https://github.com/buzzie71/TestPlugin

**Comment by totemo** [comment]
```
/petowner
```

Point at a block. Tells you the owners of pets within 2 blocks of that.

```
/spawn-tame-mob type owner
```

Spawns a dog or cat, tamed to the specified player, who can be offline. Supported types are: cat, dog, ocelot, wolf (case-insensitive).  Currently doesn't support setting the cat type because there is no CH API to do that.

**Comment by totemo** [comment]
Apparently:  spawn_mob('OCELOT:BLACK_CAT') is possible. Reopening to give this a go.

**Comment by totemo** [comment]
And fixed. Cat type is randomly selected from the three possibilities, (BLACK_CAT, RED_CAT, SIAMESE_CAT).
