### ISSUE TITLE
Particular potions currently unbrewable

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#125]
As per: https://nerd.nu/forum/index.php?/topic/359-unable-to-make-health-2-potions-on-survival/

Potions that require glowstone or fermented spider eyes are apparently unbrewable. It seems that when we removed the block for brewing night vision potions (golden carrot brewing; which should have enabled invisibility potions) we reverted back to the potion brewing setup we had back in revision 18.

This is a high priority issue as far as Survival goes, it's severely disrupting proper gameplay for many people.

**Comment by totemo** [comment]
Fixed. The problem was caused by an error in the KitchenSink configuration file that reverted the list of blocked brewing ingredients to default.
