### ISSUE TITLE
Add CH command to calculate time since last restart and time until next restart

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#128]
Have tested code, will make pull request shortly.

**Comment by tompreuss** [comment]
Also noting here that this requires

```
store_value('time'.'key', round(expr(nano_time() * pow(10, -9))))
```

to be added to main.ms

**Comment by totemo** [comment]
In place as a separate file from misc.msa on all three servers because they don't currently match each other or the github repository. They're part way through being restructured into a shared hierarchy referenced by symlinks.

**Comment by totemo** [comment]
Just noting that auto_include.ms is not the correct place to store_value() the restart time(), unlike my initial attempt, because it gets implicitly re-executed for every package file and hence the stored value is constantly re-updated.
