### ISSUE TITLE
Switch to EasySigns across all three servers.

### ISSUE THREAD

**Issue by totemo** [NerdNu/NerdBugs#129]
Note the differences in sign requirements on PVE, Survival, and possibly Creative as well.  Incorporate those capabilities into EasySigns and roll out on all three servers.

Reference: https://nerd.nu/forum/index.php?/topic/495-sign-kits-issue/

**Comment by LadyCailin** [comment]
It is installed on all three servers, however, existing signs may be using the other system. For this rev, I felt there was no need to go replace all the signs that already exist on the old system, but future signs should only use EasySigns. We could then remove the old code once new revs start on all the servers. EasySigns should be feature compatible with all the existing features of the old system, but if not, I need to add that.

**Comment by totemo** [comment]
Ah.  I wasn't following symlinks with my find command. :)

OK. In that case, we're just missing the coloured armour and an optional upper limit on the number of items to give and I think we can retire the old packages with the new revisions, as you say.

**Comment by LadyCailin** [comment]
Ah, right. Armour color. What is the upper limit for though?

**Comment by LadyCailin** [comment]
Aaand, I just read the forum post. Yep, that'll be easy to add as well.

**Comment by totemo** [comment]
I have added a 'potion' action to give a potion effect, 'leather' to give coloured leather armour and 'inventory' to give the player an exact copy of your current inventory at the time of setting up the sign.  I believe that the old signs scripts are still in use on P, Rev 11. That code can now be retired once the new P revision hits, provided we can establish that C and S no longer use the old code too.

**Comment by totemo** [comment]
I will be forcibly breaking any usage of the old signs today.

**Comment by LadyCailin** [comment]
All the servers should be up and running with easy signs now, so I'm going to close this.
