### ISSUE TITLE
Add a line to Creative /help for /empty command

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#13]
Even though the /empty command is working on C, I've been asked many times by players how to clear their inventories; people don't seem to know the /empty command exists. (I think it may not have worked for a while?)

All that should be needed is an extra line in the c.nerd.nu /help message which says:

/empty - clears your inventory.

Best place would probably be between /home and /modreq.

**Comment by jcll** [comment]
Added
