### ISSUE TITLE
Add a command to ignore pvp flag

### ISSUE THREAD

**Issue by Denevien** [NerdNu/NerdBugs#131]
We would like to have something where we can run "/pvp buzzie71" and it allows player buzzie71 to ignore the pvp deny flag of worldguard. This would allow for fun events such as admin chases, and can easily be toggled in game so presence of a tech admin will not be required.

**Comment by LadyCailin** [comment]
I'm not sure this will be trivial at all. WorldGuard does the PVP blocking by region, there's no options to override it for players. I _might_ be able to hack around this through CH, but if not, this will not be possible without a ton of effort, I think, unless someone has any other ideas that I'm missing.

**Comment by Denevien** [comment]
I know we have pvp deny set on the **WORLD** region, so is there a way to force a player to bypass the flag on the one "region"?

**Comment by totemo** [comment]
I got some way into this with CommandHelper before realising that there is no (documented) way to convert the entity ID from an EntityDamageByEntityEvent back to a specific player instance.  I think this feature is best implemented with a small custom plugin.

**Comment by LadyCailin** [comment]
You can loop through all players and use the info obtained from pinfo(), but yeah, there's a feature request to make that a one liner.

**Comment by stevommmm** [comment]
event.setcancelled(false)

onEntityDamageByEntity

priority.LOWEST

**Comment by zifnab06** [comment]
@stevommmm was close...

Anyways, I have written a plugin (aptly named "AdminHunt") which does just this. It is located at http://github.com/zifnab06/AdminHunt.

Basic commands are as follows: 

```
/adminhunt <playername>: enables (or disables) adminhunt mode for said player, and broadcasts that an adminhunt has begun.

/adminhunt-list: lists all players in adminhunt mode. 
```

This uses the WorldGuard API to accomplish this, instead of overriding the same events that wordguard does.

If any of the admins would like to see it in action, let me know, I have it running on my test server. 

Thanks!

**Comment by totemo** [comment]
@zifnab06 etc

This plugin will be available on the next P revision, if not sooner. ;)
