### ISSUE TITLE
Carto has not been updated since July 1

### ISSUE THREAD

**Issue by GMMan** [NerdNu/NerdBugs#136]
Please check on carto updating processes on the wiki.

**Comment by totemo** [comment]
Currently updating.

**Comment by totemo** [comment]
Reopening this issue as a reminder to work on this later.  Two new issues:
- The carto is not supposed to be hosted on the nerd.nu box due to the bandwidth cap.
- The version of Minecraft Overviewer we're running needs to be upgraded to cope with the terrain texture arrangement in 1.5.

**Comment by ethancedrik** [comment]
It has stopped updating again according to several players

**Comment by totemo** [comment]
Thanks.  Apparently it's been down a good long time and one of the Python packages that it's based on has gone AWOL. o.O

I'll see if I can get that back shortly.

**Comment by totemo** [comment]
Alright, I've installed the missing packages, built the latest overviewer from source and downloaded the 1.6.2 JAR for the default resource pack.  The PVE carto generation is 11% done and seems to be happy.  Will check back on this these tomorrow and reopen if there's still a problem.

**Comment by totemo** [comment]
Confirmed that PVE's run was good. Doing one for creative now.  Then daily runs will apply thereafter.
