### ISSUE TITLE
Certain Carto renders have rest of the map cut off

### ISSUE THREAD

**Issue by GMMan** [NerdNu/NerdBugs#137]
Current C carto stops at 2500, and rev 23 carto is also half cut off.

**Comment by ethancedrik** [comment]
Coolgamerovr90 here, I was going to submit this same issue, but never did, It appears that when they expanded the world border, they didn't expand the maps rendering distance, it stops rendering roughly about X 2525

**Comment by totemo** [comment]
The new cartographs are not configured to crop the map.  Re-rendering old maps uncropped is not a high priority.  Wait for the cartograph to update.

**Comment by totemo** [comment]
Reopening to note that I will be configuring a crop region for current renders once I work out exactly what that should be.
