### ISSUE TITLE
Forum links don't redirect to correct pages on main nerd.nu page

### ISSUE THREAD

**Issue by ethancedrik** [NerdNu/NerdBugs#138]
coolgamer here, This isn't a big issue at all, but when I go to http://nerd.nu/ and hover over the forums link, and click one of the links under it, for example Server Issues/ Bugs, then Survival, it redirects me to the forum home page. I assume when they switched over to IPB, they didn't change those links

**Comment by totemo** [comment]
Not a high priority, but it's a quickie and they don't feed me unless I complete my quota of 1 bug a day, so that's done.
