### ISSUE TITLE
Figure out the best method of debuffing strength potions

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#140]
As per [this ongoing thread](https://nerd.nu/forum/index.php?/topic/588-vanilla-pvp-is-broken-in-16/) it appears that the [Attribute system](http://www.minecraftwiki.net/wiki/Attribute#Vanilla_Modifiers) brought in by Mojang in the 1.6 update makes a major change to the power of strength potions, one that we're not keen on keeping on Survival, as it changes combat significantly.

I wanted to put this here as this is definitely something we want to change, but I would like the tech admins' input on what is the best solution for doing so. I don't understand how this Attribute system works, but is that something that we can edit ourselves, as a server? In the absence of that not being possible, i've had a couple of people suggest [this](http://www.curse.com/bukkit-plugins/minecraft/strength-potion-fix) as a simple solution, and I would like your input as well on whether that's suitable for us to implement or even if you know of any alternatives that would work better for us.

We'd like to have this issue figured out as soon as possible, but in the event that we can't come to a conclusion on works best in the time frame before launching the new revision, we would like to ban the brewing of strength potions (blaze powder) as a last resort. We already have this option in KitchenSink, so it's no problem to get set up and use in the meantime.

**Comment by totemo** [comment]
I hope to have a spare moment to look at that pull in a couple of days - before the launch.  Flat out at the moment.
