### ISSUE TITLE
Running /untame on a saddled horse results in an untameable horse

### ISSUE THREAD

**Issue by timovv** [NerdNu/NerdBugs#141]
With a saddle, horses cannot be re-tamed when untamed using `/untame`. The horse can be ridden and controlled, however, but with a saddle the horse does not recognise that the player is attempting to tame it. The horse cannot be used for breeding as far as I know, and the saddle cannot be removed without killing the horse.
## 

Unfortunately as far as I can tell there isn't a hook in Bukkit yet to see if the horse has a saddle. This could probably be checked via CraftBukkit, although that's far from ideal.

**Comment by totemo** [comment]
Yeah. Twoist showed me this bug yesterday.  I intend to just drop the inventory on /untame.

**Comment by totemo** [comment]
Resolved.
