### ISSUE TITLE
Could we get the Survival leaderboard refreshed for the current revision?

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#143]
This one slipped past us in the planning for the new revision (sorry folks!), but could we get the leaderboards at http://nerd.nu/survival/ refreshed so that they're showing only kills from this current revision/wipe the slate clean so that it can start logging again properly?

Thanks!

**Comment by totemo** [comment]
Don't apologise too much. The StrikeDeath database was deleted just prior to the start of the new revision.  The web page is apparently not updating correctly (I'm trying to work out what's up with that), but once it does it should reflect correct stats for the entire duration of this rev so far.

**Comment by totemo** [comment]
Needed to get the mcp-glicko2 web service running locally.

Fixed.
