### ISSUE TITLE
Update Enchantism with new config

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#144]
We've gone ahead and altered the level requirements for bow enchantments a little bit to account for the fact that you would typically nab several enchants on a bow when enchanting at level 30. Whenever one of the tech admins has a chance, we'd appreciate having [this](http://paste.thezomg.com/10707/76488548/raw/) as the updated config for Survival.

**Comment by totemo** [comment]
Available on the next restart.
