### ISSUE TITLE
Investigate changes made to NCP on Survival

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#145]
I've been informed by one of our players that following a discussion with one of our tech admins, some change(s) were made to NCP on Survival with the intention of remedying issues involving moving items around in the inventory (the issue being that sometimes items stick on your cursor (?); if that, the issue exists on other servers as well). I have also been informed that this supposed change has enabled it so that certain features of Inventory Tweaks are now possible to use, something that is banned on Survival.

I was wondering if we could have this looked into, as if it's allowing parts of Inventory Tweaks to work, then we need to discuss whether or not keeping said change is of more benefit to the server. I'm also unsure if the change to NCP was authorised by any of the other admins, if not, this needs to be addressed elsewhere as well.

**Comment by totemo** [comment]
I have a backup of that config from before I started working on the SurvivalFly warnings so it should be easy to work out exactly what was changed for FastClick and by how much.  Given my current priorities and schedule, could the S admins install Inv Tweaks and investigate the impact of the FastClick change?

**Comment by totemo** [comment]
Okay.  Well I now know what was changed.  We can discuss in-game how best to proceed.  I think it will require some experimentation.

**Comment by totemo** [comment]
That check was disabled completely by another tech so it's not surprising that Inv Tweaks worked.  I re-enabled the check and increased some thresholds some time ago.  Survey of the staff today tells me that there have been no complaints about it in game.  Closing as presumed fixed.
