### ISSUE TITLE
Investigate RebalanceVillagers Villagers not Selling HorseEggs

### ISSUE THREAD

**Issue by draykhar** [NerdNu/NerdBugs#146]
Villager class '6' (a green villager) is a custom villager meant to act as a stablemaster - buying wool and iron and selling Saddles and Horse Eggs. It's not properly selling said Horse Eggs.

relevant Configs:
https://www.dropbox.com/sh/eifx7f22uhwb3tw/t54vXdSJrA

**Comment by totemo** [comment]
I looked at the configuration.  For items with damage values you need the following syntax:

> ```
>    '6':
>         buys:
>              cloth: 0.5
>              ingotIron: 0.3
>         sells:
>             saddle: 0.2
>         other:
>             horse-egg:
>                 probability: 0.2
>                 buyA:
>                     item: currency-item
>                     amount: [9, 25]
>                 sell:
>                     item: '383'
>                     damage: 100
> ```

I've configured that and we'll see how it goes on restart.

**Comment by totemo** [comment]
Changed cloth to currency-item as requested.

Confirmed as working in-game today.  I'll mail you the updated config via the forums.
