### ISSUE TITLE
Re-enable /mode for users on Creative

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#15]
We used to have /mode available for players on Creative.  It's a great way for players to be able to interact with their creations survival style, and makes builds like obstacle courses much more workable.  I know a lot of C players were using it based on the number of people we had to manually /mode back to creative after disabling it.

I know one of the issues was preventing ice from turning into water, but I think we may have ways to fix that now? Were there other bugs preventing us from bringing this back, and if so, can we fix them?

**Comment by stevommmm** [comment]
This should do it.

https://github.com/NerdNu/KitchenSink/commit/b103176116ae88182952954e57ddb47114fc86f7

Untested code.

**Comment by ghost** [comment]
For the sake of record: Tested and working on a local server.

**Comment by stevommmm** [comment]
Just tested on C. Ping a tech when a C admin is around to add the /mode command permission to the default group.
