### ISSUE TITLE
/clanchat confirm delete no longer works

### ISSUE THREAD

**Issue by ethancedrik** [NerdNu/NerdBugs#150]
So on S, I was messing around with ClanChat and created a channel called "test1", then I tried to delete it, so I ran /clanchat delete test1, and then /clanchat confirm delete. When I ran /clanchat confirm delete, nothing happened. I tried it multiple times, and still nothing happened. If I were the one maintaining ClanChat, I would just alias /clanchat delete #Channel to /clanchat leave #channel, since leaving a channel that you are the owner of does indeed delete it.

**Comment by zifnab06** [comment]
Just tried on survival:

/clanchat create test8
/clanchat delete test8
/clanchat confirm delete

channel #test8 has been deleted. Not sure what you're doing wrong.

**Comment by ethancedrik** [comment]
It was because I sent a pending invitation to IAmARelaybotAMA
I tried it once again
/clanchat create deleteme
/clanchat delete deleteme
/clanchat confirm delete
and it deleted it
I noticed when I had sent the invitation and tried to delete it, I didn't get the red warning message, but when I did delete the channel with no pending invites, it showed the red warning before the confirm message and deleted it right away, I guess this issue is solved
