### ISSUE TITLE
Give moderators in ModMode access to /signtext

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#151]
If this warrants discussion for the other two servers, i'll specify that this is wanted on Survival in particular. Giving moderators access to the /signtext command (which allows you to add text to a sign with a command whilst facing it, as opposed to needing to break and replace the sign as necessary) will make tasks such as editing the signs in the Clan Hall a decent amount easier - particularly when there are modreqs requesting that existing clan members be added/removed. I'd like to extend this useful tool to the moderators, and not have it reserved just for admins.

**Comment by LadyCailin** [comment]
This is easy enough. I see no reason not to give this to mods on all servers too. Abuse can easily be tracked. I'll change this shortly.

**Comment by LadyCailin** [comment]
Added.
