### ISSUE TITLE
add [Server] Alerts for Usage stats and Chat relay

### ISSUE THREAD

**Issue by ethancedrik** [NerdNu/NerdBugs#153]
[Edit] NerdBugs isn't the place for stuff like this, as I have now realized. I will refrain from using this as a place to post suggestions from now on. This suggestion isn't important, as the Usage stats are still in Beta and being tested, and everyone now knows about the chat relay because of a subreddit post, and when they ask in game their question can easily be answered by another player. Sorry about this. It seems like totemo is closing a lot of issues similar to this one. Please remember that NerdBugs is for technical issues and problems with certain plugins. If it is a suggestion, or a non technical issue, then please take it up somewhere else. This gets in the way of more serious issues, as I have been doing myself

**Comment by tompreuss** [comment]
Server admins manage their own messages with the [new-ish /alert command](https://github.com/NerdNu/nerdCH/commit/b3969904bb5536bbe0ea9fa31dfa0c1943a3da36); as such this ticket is unnecessary.  Please contact a server administrator (via /msg or /mail in game, forum PM, or reddit PM) with your ideas for potential server messages.
