### ISSUE TITLE
Survival - Disable Splash Potions In Spawn

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#154]
You can hit people with splash poison/damage/etc potions in spawn.  Please set the appropriate worldguard flag to prevent this. (potion-splash deny or invincible allow?  Invincible would also stop the fall damage you take from changing levels in spawn, if you felt like doing it that way.)

**Comment by totemo** [comment]
potion-splash deny set in the spawn_nopvp region.  This is actually not a good candidate for a bug as it is well within the capabilities of a server admin to do this.

If denying potions splashes in spawn interferes with some feature of spawn I'm not aware of, I'm sure the sadmins will re-allow it.
