### ISSUE TITLE
Survival - People with PVPTimer on can pickup items

### ISSUE THREAD

**Issue by FourDown** [NerdNu/NerdBugs#156]
On S, people that still have pvptimer enabled are able to steal your loot from kills. There is a config option in pvptimer to disable that.

**Comment by totemo** [comment]
If that option was enabled, it would mean that players cannot gather resources (wheat seeds, logs) or pick crops until they removed the PvP timer.  It would negate a lot of the benefit of a 60 minute protection for new players.

At this stage I think this is a policy issue and not a bug.  Although the solution is technical it does not belong here.  Take it up with the sadmins.
