### ISSUE TITLE
Survival - Walking on Carpet Kicks You For Flying.

### ISSUE THREAD

**Issue by FourDown** [NerdNu/NerdBugs#157]
Walking on stacked carpet will kick you for flying.  For example, climbing the carpet stack at (-25, -215) will always kick you.

**Comment by totemo** [comment]
I've been unable to replicate this problem at that exact location.  As of yesterday, the violation level for survival fly kicking is now a fairly sizeable number.  Do you have any client modifications that could be affecting your movement?

**Comment by totemo** [comment]
Never mind.  Perhaps I have a bypass permission.

Switched to a Beta build that's meant to resolve the issue (http://dev.bukkit.org/bukkit-plugins/nocheatplus/tickets/593-towering-with-carpets-triggers-survival-fly/).  See what happens on the next restart.

**Comment by totemo** [comment]
Fixed.

**Comment by nopresnik** [comment]
Let's ride the magic carpet!
