### ISSUE TITLE
Survival - Some Combat Logging does not trigger "[Player] Chickened Out"

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#158]
It's hard to test the specifics of this bug, because it requires one party to break the rules.  But if you hit someone from far away with a bow, they can still log out without triggering the "[Player] Chickened Out" announcement.

**Comment by totemo** [comment]
Looking at the NoLog code it ignores logged PvP damage if the player logging out has no entities within a 20x20x20 cube centred on himself.

**Comment by roastnewt** [comment]
Closing, since survival has moved to combat tag and this is not longer an issue.
