### ISSUE TITLE
UDP query is nonfunctional on all 3 servers

### ISSUE THREAD

**Issue by ethancedrik** [NerdNu/NerdBugs#160]
Hi, It seems as if UDP/Gamespy query has stopped working, and it looks like someone disabled it on C. I know that the server listings on MinecraftForums are dependent on it, or else it will say that the server is offline. I originally sent this to outage@nerd.nu, but was told to come here as it is better suited for NerdBugs, since I didn't know where to report this. I was using the iOS app FriendCraft to query them at the regular UDP query port, if that helps

**Comment by totemo** [comment]
The servers have been taken down for security reasons.   However, I've just confirmed that the UDP query configuration of all three servers and the firewall have not changed.

Once they're back up, I'll confirm with http://dinnerbone.com/minecraft/tools/status/

**Comment by nopresnik** [comment]
@totemo presuming the security risk is in bukkit, I believe that has already been patched.

**Comment by ethancedrik** [comment]
Thanks totemo, it really isn't that big of a deal to me, as /list-all is a way better method of seeing who is online on all 3 servers,  but it seems like it could cause some problems in the future with the websites we advertised on. I guess it wasn't disabled on c. The reason why I thought that was because I could still reach S and P as having query enabled, but C returned as if it didn't have query at all, weird.
Edit: Just tested this with Dinnerbone's query tool. S responded to the query request at port 25565, but C didn't, and reported itself as being offline

**Comment by totemo** [comment]
Still working for me.

**Comment by ethancedrik** [comment]
@totemo They have started working again for me, too. Thanks :)
