### ISSUE TITLE
Extend certain WorldGuard permissions to moderators on Survival

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#162]
Currently on Survival moderators do not have permission to create regions, nor add flags to existing ones. This was an administrative decision made some time ago, not a bug, but the current admin team would appreciate these being restored to moderator permissions. We have a multi-use arena on Survival, where regions need to be altered to switch between the appropriate 'moderated' and 'public' arena states, and it's impossible for moderators to organise these without admin intervention with our current setup.

We would really appreciate if these could be remedied whenever possible. I'm unsure to what extent moderator's current permissions are with WorldGuard, I just know the aforementioned creation and adding flags is apparently not possible. Lining them up with whatever is available on Creative, for example, might be suitable (as I understand only admins can do PvP regions on PvE, for example, and that's not suited to Survival).

**Comment by totemo** [comment]
Done.  Only usable by moderators in ModMode.  Added the region tools to the mod kit.
