### ISSUE TITLE
All caps limiter is no longer functional on Survival

### ISSUE THREAD

**Issue by ethancedrik** [NerdNu/NerdBugs#163]
Hello, I am sorry that I have been creating so many NerdBugs reports lately, I am not trying to create unnessesary/unneeded ones at all. If it is starting to come off as that please tell me. Some time ago I recall a bot net of accounts joining Survival, and spamming chat with all caps messages, I tested this out myself later on, and the spam prevention feature, which tells you "Please don't use all caps!" and dosen't send the message to global chat is completely gone, only on Survival. I know that it is still there on Creative and PvE, as I tried saying a player's name which just happens to be all caps on PvE, and got the message. I am unsure if there was a specific reason to this, like a plugin conflict, but I do see this as a bug and a feature that has stopped working.

**Comment by zifnab06** [comment]
This hasn't been enabled on survival for at least the last two revs.

**Comment by totemo** [comment]
That's by configuration in KitchenSink and it's exactly how the S admins want it, I believe.
