### ISSUE TITLE
Make easy signs easier to edit

### ISSUE THREAD

**Issue by totemo** [NerdNu/NerdBugs#164]
Currently easy signs have to be remade from scratch just to change the order of actions or insert an action early in the sequence.

Proposed additions:

/easy-sign list
    List the current actions associated with a sign.  Sign actions are numbered in the listing so that they can be referenced by later commands.

/easy-sign remove <number>
    Remove sign action by number.

/easy-sign reorder <old> <new>
    Move sign action at position number <old> to position number <new>.

/easy-sign delete
     Alternative syntax for /easy-sign-delete.

**Comment by tompreuss** [comment]
Another proposal (not related to editing signs, but for a new sign):

/easy-sign lore
A variation on /easy-sign take that checks for lore metadata match to argument provided

**Comment by totemo** [comment]
Yup. Just looking at the far reaches of commands.msa now and I see we have /easy-sign-info that does more or less what I want for /easy-sign list. I'll modify that.

**Comment by totemo** [comment]
- Numbered the actions in /easy-sign-info output. 
- Added /easy-sign-remove to remove an action.
- Added /easy-sign-reorder to reorder actions. 
- Added a cart action to spawn a minecart.  Can be used to trigger redstone using a tripwire. Then dump the cart in lava.
- Added a lore action to take if item has matching lore. Read the docs carefully: http://redditpublic.com/wiki/EasySign
- Added commented out drop and dropinventory actions. The former would place an item with 0 velocity and let it fall.  The latter would scatter a copy of the player's inventory as occurs when they die.  I think I need additional CH APIs to do those.
