### ISSUE TITLE
In relation to Doppelganger, an idea for the rare stonebrick variants.

### ISSUE THREAD

**Issue by Trooprm32** [NerdNu/NerdBugs#165]
I thought of this idea, and thought it would be a neat addition to the doppelganger plugin.

If I understand how Doppelganger currently works, this would go along with the renaming the pumpkin/jack to one of the three variants of stonebrick. Those being; Chiseled Stone Bricks, Cracked Stone Bricks, and Mossy Stone Bricks.

The idea would be to spawn an Iron Golem lookalike using X Base block and said specific renamed pumpkin. The golem would then spawn like normal, and immediately be hostile to the closest player to them within X range.
Golem health and strength will have to be scaled to a reasonable length to avoid excessive farming, preferably not able to be solo'd. After the golem dies, it will drop X number of blocks as the reward.

**Comment by tompreuss** [comment]
In regards to P: it'll be a slightly different mechanic than what you describe due to limitations on how mobs and drops work, but the end result you're looking for will be in place next revision.

Stay tuned.

**Comment by totemo** [comment]
I'm closing this as "implemented", give or take.

http://www.reddit.com/r/mcpublic/comments/1n8830/pve_revision_12_information_post/
