### ISSUE TITLE
Update Fishchecker

### ISSUE THREAD

**Issue by DaneEveritt** [NerdNu/NerdBugs#166]
The version of `Fishchecker` being used is out of date. The most current version is 0.9. This version changes API calls, and implements Glizer support and fixes a bug with Minebans results.

It also removes the need for a 301 redirect to occur, reducing the latency for data.

http://dev.bukkit.org/bukkit-plugins/fishchecker/

Thanks,
Fishfish0001

**Comment by totemo** [comment]
A grep through our logs shows that we are in fact using version 0.9 and have been since May.  What leads you to believe that our version is out of date?

**Comment by DaneEveritt** [comment]
@totemo Sorry, I'm the owner of Fishbans, I mis-read our logs and it looked like you guys were on the older version. We are trying to cut back on the amount of double requests. Sorry about that. :)

**Comment by totemo** [comment]
Ah thanks.
