### ISSUE TITLE
Add kill streaks to Survival*

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#17]
Two types of kill streak to consider:
- Consecutive PVP kills without dying from PVP (milestones at 5, 10, 20, etc.)
- Multi-kills, i.e. quickly killing multiple people in a row.  Could be implemented via a counter which increments by 1 every time a player kills someone in PVP, but resets to 0 after X (= 10?) seconds have passed without a PVP kill.

DeathTpPlus had both, when we used to run it.
http://dev.bukkit.org/server-mods/deathtpplus/

*pending S admin approval

**Comment by stevommmm** [comment]
Need to add a timestamp field to the database.

Need to get a seperate thread with a queue going for database interaction stuff.

Once we have the timestamp I would like to go with erisian's idea of X kills in 2 minutes type messages, rather than 'streaks'.

**Comment by ghost** [comment]
I wrote up a plugin using player metadata to hold the killstreak info. It allows fully configurable 'levels' and corresponding messages. I also included an optional 'juggernaut' threshold which allows you to set either player compasses pointing to the last kill, potion effects on the juggernaut, or both. Killstreak information is destroyed on player login.

Still got a bit of work to do (I want to deny juggernauts from accessing chests so they don't just chest their stuff among other things) but I briefly ran it by dan1son.

https://github.com/SyntaxNode/Dreadnaught

**Comment by stevommmm** [comment]
Awesome work!

Unfortunately we already have StrikeDeath which does all our kills database logging ( and is needed for the leader board )

I guess we could run two pvp stats plugins if need be, but just seems wasteful.

Mind if I just roll this functionality into it? or you do?

**Comment by ludeman84** [comment]
Relevant, regarding the Dreadnaught plugin:
http://www.reddit.com/r/mcpublic/comments/12fnle/regarding_dropping_heads_dreadnaught_my_plugin/

**Comment by ghost** [comment]
Dreadnaught now runs the exact same schema as KillDB / StrikeDeath, which makes replacing it with additional functionality seamless.

**Comment by ludeman84** [comment]
Most recent update on our strategy for this:
http://www.reddit.com/r/mcpublic/comments/18ax4p/dreadnaught_the_last_thing_i_have_for_mcpublic/

Thanks to SyntaxNode for the time he's put into this.

**Comment by slide23** [comment]
Implemented with [KillStreaks](http://dev.bukkit.org/bukkit-plugins/killstreaks/)
