### ISSUE TITLE
Enchantism is outdated

### ISSUE THREAD

**Issue by timovv** [NerdNu/NerdBugs#170]
A couple of weeks ago I committed some changes to Enchantism. Changes include a way to access the vanilla enchanting UI (configurable) and some minor performance optimisations.

I don't mean to be pushy. This this merely to serve a reminder that it should be done at some point.

Thanks.

**Comment by totemo** [comment]
Ah, thanks for the reminder.

**Comment by totemo** [comment]
Updated, thanks.
