### ISSUE TITLE
Issue with /i and wools

### ISSUE THREAD

**Issue by ethancedrik** [NerdNu/NerdBugs#179]
Whenever I type /i blackwool for example, I get a CommandHelper CastException Expecting an integer, but received 35:15:0 instead <<maincode>>:inventory.msa:7

What I assume is going on is that it is not recognising wools correctly or refusing the item number

Someone in IRC suggested that I try /i 35:15 which worked, but /i 35:15:0 didn't work.

I assume someone needs to edit the inventory.msa and remove the extra zero after that wool item number

**Comment by ethancedrik** [comment]
totemo has fixed this now, everythings working again :)

**Comment by totemo** [comment]
Thanks for reporting.
