### ISSUE TITLE
Sync up /trace and /trace-r with /lbrb and /lbrb-r

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#18]
One of our current moderating best practices is to always /trace-r wherever you plan to /lbrb-r, with the same radius for both, to see exactly what it is you'll be rolling back.  The same ideas apply for /trace and /lbrb, as well.

At the moment, the /trace commands and /lbrb commands are not synced, in the sense that edits appearing in the trace/trace-r will not always be rolled back by the lbrb/lbrb-r.  I think this may just be a question of the time window each alias uses, but I don't know for sure.

For example, this /trace:
http://i.imgur.com/ZMHln.png

Yielded this rollback:
http://i.imgur.com/QLyUM.png

If it is just a question of how far back it looks, I think the ideal solution would be to extend the time window for /lbrb and /lbrb-r, but I know that was originally changed to avoid rolling back xrayed ores without also rolling back xrayed stone.  I'm not a fan of that setup in general, and would rather we shorten the time ores spend in the history to be the same as stone.  Alternatively, we need to shorten the time windows for /trace and /trace-r to show only what will be rolled back, even if that leaves out edits that are still in the database.  I would prefer the former option, but regardless of what we do traces should match rollbacks exactly.

**Comment by LadyCailin** [comment]
I _think_ this was fixed a while back, is it not?

**Comment by ludeman84** [comment]
Nope - as a test on S, I found some griefing that dated back to Feb. 5th - /trace-r identified the blocks as having been griefed, but then when I ran /lbrb-r for the same person and radius, it didn't find anything.

**Comment by LadyCailin** [comment]
Fixed on all 3 servers ^_^
