### ISSUE TITLE
No displayed results from /find-pets <range>

### ISSUE THREAD

**Issue by Denevien** [NerdNu/NerdBugs#182]
If I just do "/find-pets", it returns the how-to examples, but if I fill in a range, it returns nothing. There is no error, just nothing. It worked when I was set as PAdmin, so maybe error of perms as a HAdmin

**Comment by totemo** [comment]
HeadAdmins have the same permissions as PAdmins and Techs on P.  Say 3 Hail Marys, curse bPermissions twice and relog.
