### ISSUE TITLE
Cant join server.

### ISSUE THREAD

**Issue by Urrby** [NerdNu/NerdBugs#183]
Ive tried on current version, 1 befour but nothing wokrs. Every time i try to connect this appears http://i.imgur.com/j7EVEjX.png?1
Please help!

**Comment by slide23** [comment]
You should be using 1.7.4 or 1.7.2, what host are you attempting to connect to? You can use c.nerd.nu, p.nerd.nu, s.nerd.nu and nerd.nu

**Comment by ethancedrik** [comment]
Don't use Direct connect, add it to your server list
