### ISSUE TITLE
Inventory Warning Shows Wrong Time To Restart

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#185]
The warnings that pop up when you are opening chests / inventory / etc when a restart is near warn that a restart will occur in 60-90 seconds, even when the restart is less than 5 seconds away.

**Comment by tompreuss** [comment]
See #184.

`/nextrestart` and the inventory opening warning use [a value stored by KitchenSink](https://github.com/NerdNu/KitchenSink/blob/master/src/nu/nerd/kitchensink/KitchenSink.java#L270).

The restarts are scheduled by mark2.

Right now they don't agree nicely but once #184 is cleared up it should be better.

**Comment by roastnewt** [comment]
Ah, I assumed because they were off by more than 30 seconds, that it wasn't the same issue as #184, because @totemo made it seem like that issue was only responsible for a few second disagreement.

**Comment by roastnewt** [comment]
Closed, duplicates #184
