### ISSUE TITLE
Running /place while in a minecart/horse dismounts you

### ISSUE THREAD

**Issue by coolgamerovr90** [NerdNu/NerdBugs#187]
While in a minecart/horse or other moving vehicle/entity, if you run /place [Place name here] you will be taken out of whatever you are riding when you get pointed in the right direction. I assume this can be fixed by having the script detect if you are in a vehicle or not and if you are riding something, have it not point you in the direction of that place, but still show the place info.

**Comment by slide23** [comment]
Fixed
