### ISSUE TITLE
Survival Rev 22 Cartograph

### ISSUE THREAD

**Issue by Mrloud15** [NerdNu/NerdBugs#188]
Generate and upload rev 22's carto to http://redditpublic.com/carto/survival/.

**Comment by totemo** [comment]
The cartos for revs 21 and 22 are generated as of a couple of weeks ago.  Poke Deaygo again.

**Comment by Deaygo** [comment]
Both are uploaded.  Just waiting for a picture for S22 to put up and this can be closed.

**Comment by Deaygo** [comment]
All done.
