### ISSUE TITLE
Animals spawned in via /spawn-tame-mob do not persist after chunk unload

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#189]
Animals spawned in via [`/spawn-tame-mob`](https://github.com/NerdNu/nerdCH/blob/master/LocalPackages/pve-only/pets.msa#L20-L68) do not persist after chunk unload

Steps to reproduce on P (command is pve-only):
1. `/spawn-tame-mob cat tompreuss black_cat`
2. _cat appears_
3. teleport away to unload chunks
4. count to three
5. teleport back
6. _cat no longer exists_

Expected behavior is that the cat does not despawn.

---

Prior troubleshooting attempt with @totemo on 2014-01-03:

```
<totemo> In testing, disabled MobLimiter, WorldGuard, WorldBorder, KitchenSink, etc etc
<totemo> Kept bPermissions, CommandHelper, NerdSpawn, TPControl, WorldEdit.
<totemo> Tame cats spawned by command disappear as with hostile mobs.
<totemo> at this stage it is either Bukkit/Spigot itself or CH
```

_upgraded CH, other CH stuff broke_

```
<totemo> So I did upgrade CommandHelper and now I am seeing CastExceptions in the server log
<totemo> so apparently the new CH breaks a bunch of stuff
<totemo> I'm going to put the old version of CH back and restart shortly
```

_other CH stuff was fixed_

---

In my testing done today using the exact builds of Spigot and CH that P currently uses (@slide23 told me which ones), and only having WorldBorder, WorldEdit, WorldGuard, and CommandHelper installed in my test environment, I was unable to reproduce the issue we experience on P.  My spawned mobs persisted after chunk unloads, restarts, etc.

Additionally, using the latest Spigot ([1260](http://ci.md-5.net/job/Spigot/1260/)) and CH ([2562](http://builds.enginehub.org/job/commandhelper/4166/)) builds in my test environment worked fine as well.

To aid in your search for possible causes: as for the timing (when this stopped working for us) it was some time before 2013-12-20, and possibly as early as before 2013-11-20, based on the best of my recollection.

As always, I'm more than happy to help with any troubleshooting or testing this may require.

**Comment by LadyCailin** [comment]
As to the issues with CH, there were a few builds that were derpy, but as far as I know, CH is stable on the current builds.

http://wiki.sk89q.com/wiki/CommandHelper/Staged/API/set_entity_persistence This function can be used to make an entity persistent, which should be done for pets. I guess that never came up before, because in things like arenas and such, that's probably desired, for them to NOT be persistent. Anyways, should be a one line change.

**Comment by LadyCailin** [comment]
Fixed!
