### ISSUE TITLE
/version command returns nothing on S/P/C

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#191]
/version command returns nothing on S, P, or C. Seems to work fine on lobby though

**Comment by tompreuss** [comment]
Not a bug, it's intentional: see [here](https://github.com/NerdNu/nerdCH/blob/master/LocalPackages/misc/pl.msa#L135-L144).

**Comment by mattman00000** [comment]
So, it intentionally does nothing but silently inform the mods that you've checked the version?

Is there some nefarious use of /version I'm unaware of?

**Comment by LadyCailin** [comment]
Information hiding is a well known security practice.
