### ISSUE TITLE
Creative Revision 25, Survival Revision 23 & PvE Revision 12 Cartographs

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#193]
I've been working on cleaning up the wiki somewhat over the last couple of months, and I noticed these are the most recent cartographs that need uploading. If there's anything I can do on my end (as a wiki user) to help sort out / expedite this process in any way in the future, then please let me know :)

**Comment by tompreuss** [comment]
P rev 12 carto is at [nerd.nu/maps/pve12/](http://nerd.nu/maps/pve12/), not sure if it needs archiving/moving to [redditpublic.com/carto/pve/](http://redditpublic.com/carto/pve/) or if a link just needs to be put there to the other location.

**Comment by coolgamerovr90** [comment]
I have never seen any previous revisions map at the nerd.nu address, I also thought that they haven't been uploaded until I saw that. I always remember previous revs maps at redditpublic.com and only the current ones on nerd.nu

**Comment by slide23** [comment]
All cartos have been moved to redditpublic.com/carto/
