### ISSUE TITLE
Upload S rev 23 final save and carto

### ISSUE THREAD

**Issue by Mrloud15** [NerdNu/NerdBugs#198]
Upload the final save and carto for survival rev 23. I believe the carto is already generated, and here is a photo for the cover that should be the right size: http://i.imgur.com/s825byo.png

**Comment by slide23** [comment]
Map: http://mcp-dl.com/survival-rev23.tar.gz 
Carto: http://redditpublic.com/carto/survival/s23/#/70/64/-67/-7/0/0
