### ISSUE TITLE
Suggestion: new lwc option

### ISSUE THREAD

**Issue by Aypop** [NerdNu/NerdBugs#199]
I was wondering if a new lwc mode would be possible in which any player or permission group can open a chest to observe its contents, but only the owner or the owner's permission group can either take out items or put in items. /cobserve or /cmodify observe (I don't care much for the name, but you get the idea).

Would nerd nu benefit from this additional option? I was thinking of starting a redstone academy/museum of sorts, but items in hoppers and comparators might be sticky considering players can just take out items if permissions are public and can put in items if permissions are /cdonation.

**Comment by tompreuss** [comment]
LWC is not written by nerd.nu techadmins, you may want to direct your feature requests for it to [Hidendra/LWC](Hidendra/LWC).

As a possible workaround for your proposed usage case: if you have a donation chest with the all of non used slots filled with filler items (light gray stained glass panes, cobble, etc.) then players not set to ADMIN on the chest will be unable to move them within the chest or add any items that aren't already in the chest.  And if you also don't want players to be able to add to the stacks of items in the chest, you can uniquely name them on an anvil.
