### ISSUE TITLE
/check change

### ISSUE THREAD

**Issue by nsh22** [NerdNu/NerdBugs#2]
It would be useful to have /check show any modreqs that are being worked on at the moment, rather than saying you have no open modreqs. This can be confusing and may lead to extraneous mod requests.

**Comment by stevommmm** [comment]
We implemented the current system to show users information about their own requests only, this was a design decision as not all modreqs should be publicly viewable. Many - like admin requests - contain coordinates or other sensitive information that we do not wish people not included on staff to gain access to.

If any other techs disagree feel free to reopen this, but a global /check is not something we are giving out access to.

**Comment by nsh22** [comment]
Oh sorry for my bad wording, I meant reqs the player submitted and are currently being worked on. My bad. 

Sent from my HTC

----- Reply message -----
From: "Stephen Mcgregor" reply@reply.github.com
To: "nsh22" neal_hughes@live.ca
Subject: [NerdBugs] /check change (#2)
Date: Wed, Jul 18, 2012 5:41 pm

We implemented the current system to show users information about their own requests only, this was a design decision as not all modreqs should be publicly viewable. Many - like admin requests - contain coordinates or other sensitive information that we do not wish people not included on staff to gain access to.

If any other techs disagree feel free to reopen this, but a global /check is not something we are giving out access to.

---

**Comment by stevommmm** [comment]
Gotcha, I was unaware that was not the current way of doing it, reopened

**Comment by ludeman84** [comment]
Just to clarify, the issue is that when a user runs /check, they only see modreqs placed by them which are _open_, not modreqs placed by them which are _open_ OR _claimed_.  Just tested that this is still the case, on P.

**Comment by LadyCailin** [comment]
Fixed ^_^
