### ISSUE TITLE
Fix nerd.nu/usage pages

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#20]
The hours stats are obviously incorrect.
http://nerd.nu/usage/survival/
http://nerd.nu/usage/pve/
http://nerd.nu/usage/creative/

c45y and I spent some time looking at the script the other day.  We think the issue almost certainly involves some logins/logouts not being caught in the logs.  For example, the following two commands are consecutive log entries for Kohlse:

2012-09-11 18:04:40 [INFO] Kohlse [IP removed] lost connection
2012-09-11 18:05:02 [INFO] CH: Running original command on player Kohlse ----> (command removed)

Obviously there's a missing login in there.

We're replacing the login/logout messages with null strings in some cases (notably modmode under certain conditions); is it possible we're doing this in other cases, as well?  This is clearly not just a mod issue, since the player stats are borked for everyone, not just mods.

**Comment by joealcorn** [comment]
It's also worth noting that no player disconnections are shown on planned restarts and crashes, so the script will need to account for those (I'm not sure if it does already, I've seen a version of it which didn't, but am not sure if is the same one which is currently running. Either way, I updated the one in the gitlab repo to work correctly)

**Comment by barneygale** [comment]
The gitlab one was cobbled together quickly from the older script (which I think nat wrote) so I can't attest to its correctness. It might, however, be better laid out and a decent replacement for the old one. It's less resource intensive etc.

**Comment by stevommmm** [comment]
Removing myself as an assignee, this is all being rolled into new nerd site and I have had no involvement in that so far.

As far as the log issue goes buttscicles fix should work if I understand the issue correctly.

For future tracking should we look at a plugin based solution rather than parsing log files?

**Comment by slide23** [comment]
Mostly fixed so far. Doing a bit more final testing.

**Comment by ludeman84** [comment]
Related post:
http://nerd.nu/forum/index.php?p=/discussion/18104/usage-stats/p1

Can the stats go further back without any added load effort? I assume we track everyone but only display 1000.

**Comment by ludeman84** [comment]
More recent post on the topic:
http://www.reddit.com/r/mcpublic/comments/1cty3t/can_we_get_an_actual_update_to_the_usage_stats/

**Comment by barneygale** [comment]
There's code knocking around for this in the 'new website' code - probably of some use to you. I don't have it on my current computer. iirc it just did some simple log parsing (but in a tidier fashion than the current stuff)

**Comment by ethancedrik** [comment]
All of them are working again, except survival, as Issue #124 states

**Comment by LadyCailin** [comment]
I'm currently working on this. I'm creating an all new format, which ties into the game with CH, and outputs the data with a PHP script. I'm doing limited testing atm, and we will see how efficient and how well this works. (It took like an hour to put together, so if it doesn't work, no huge loss.)

**Comment by LadyCailin** [comment]
I'm going to close this ticket, and leave the other one open, issue #124, since both of these are basically the same.
