### ISSUE TITLE
Allow all caps for player names

### ISSUE THREAD

**Issue by GMMan** [NerdNu/NerdBugs#200]
It tends to be somewhat frequent that when greeting a player who has many upper case letters in their name, KitchenSink prevents the message from being sent because it is seen as all caps spam. A sample message that gets caught is "Hi ROCKONN!". If it's not too big of a hit to performance, when too many upper case characters are detected, obtain a list of players, and for each player do message.contains(player_name). If a match is found, subtract the number of upper case characters of the player name from the number in the message. Do this for all player names, and at the end recalculate the number of upper case characters in the message, then block if there are still too many.

**Comment by Denevien** [comment]
Should be fixed in this PR: https://github.com/NerdNu/KitchenSink/pull/36
