### ISSUE TITLE
Name Change Mail Notification Glitch

### ISSUE THREAD

**Issue by ghost** [NerdNu/NerdBugs#205]
I recently reverted my name to my old name i had for over 2 years. I went from Crusader1305->Realslimeshady->Crusader1305. After changing my name I keep getting the notification that I have one unread mail message. I dont have any. About every 3 seconds it repeats the message, spamming my chat box to hell. Hopefully this problem can be solved. This happened on PvE, but could possibly happen to someone else on S or C.

**Comment by slide23** [comment]
Is this still happening? I can't find any incoming mail for you and your account is correctly seeing the name changes.

**Comment by iamdarb** [comment]
This is happening to me currently. I changed my name back to iamdarb from Darb and it's showing that I have 2 unread messages... constantly. I've manually read through everything again, but it hasn't corrected the issue. I've even cleared all of them, but am still having the same issue.
Edit: No longer happening to me.

**Comment by slide23** [comment]
@crusader1305 @iamdarb both of you should be fixed now.
