### ISSUE TITLE
Configure dispensers on C to interact with minecarts and boats only

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#22]
We don't want dispensers on C to be able to drop items, creative entities, or add/remove water/lava.  However, there are a lot of really cool things that can be done with dispensers as far as automatically generating minecarts and boats.  If it is possible to allow the latter, while still denying the former, we should be able to unban dispensers on C (which also allows its use as a decorative block).

**Comment by stevommmm** [comment]
Thanks to Nullsquare for the commit.

https://github.com/NerdNu/KitchenSink/commit/05f95a7e28300e8cbfc154163faaba050e6f8938

Just need to sort it all out and figure what we want to enable on C

**Comment by stevommmm** [comment]
Built and configured on C.

Tested carts last night, we are all groovy

Water and crap can't come out, no leaky dispensers.

Closing - reopen if issues are reported or request details are altered.
