### ISSUE TITLE
Create working IRC chat relays again

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#26]
The question of who could access such relays is an open policy question.  However, there is no doubt that this was a useful tool for server administration, and would potentially give us the option to expand to other chat configurations in the future.

**Comment by barneygale** [comment]
My plan was to pipe server output to a redis pubsub and do live logs on the new site via SSEs. Would use the website auth. I think IRC will be too much of a pain to get working, and this would offer more flexibility (e.g. mods could see /mb, NC warnings, etc). The old IRC relays are still knocking about on the nerd box somewhere.

**Comment by barneygale** [comment]
mark2 has decent support for IRC relay. All you need now is to set up an IRC bouncer and enable it.

You may (possibly) have to switch away from GameSurge if you're hitting flood limits. Zimsky and edk run [rozznet](http://www.rozznet.net/) and will happily give mcpublic a flood exemption. This may or may not be necessary.

**Comment by barneygale** [comment]
Lord knows I tried to get us a flood exemption on gamesurge...

**Comment by barneygale** [comment]
Hi all,

I asked jcll (I think?) about this a couple of months ago, and he said that @Deaygo was working on something to give a live chat relay on the website.

One question to consider is how long this might take; I know tech time can be stretched pretty thin. If it's going to take over a month or two, perhaps you should consider running IRC relays as a stop-gap measure? mark2's IRC client is pretty decent, or you could give CraftIRC another go and see if its performance is any better nowadays?

I for one found the IRC relays really useful for answering the questions of new players, and spotting when to jump in-game if trouble was flaring up!

**Comment by ethancedrik** [comment]
I would really like to see IRC relays on Nerd.nu, I've been on 4 different minecraft servers that have had IRC relays and they seem to actually make it easier for staff members to help out issues that players are having, and make server chat easily accessible from a phone or other device that has an IRC client on it. I know there is a #RedditMC-S channel on GameSurge, forty_two seemed to be the only person in it, meaning that Survival isn't linked to IRC at all. barneygale mentioned above that there may be some problems with running it on GameSurge, so I'm not sure how that will go. Using mark2's IRC capabilities seems like a easier way to do it then using a separate IRC plugin, but using something like CraftIRC might be easier for admins and mods to manage. I know that Deaygo's been very busy lately and has dedicated alot of his time to the servers too, so I really don't know if this is still being worked on at all

**Comment by edk0** [comment]
I've thrown together a relay based on a Minecraft client that's currently running on [creative](http://glin.es/chat/creative), [pve](http://glin.es/chat/pve) and [survival](http://glin.es/chat/survival), as well as outputting on IRC to the old #RedditMC-<em>C/P/S</em> channels on GameSurge and #creative, #pve and #survival on rozznet (where the bot has a flood exemption).

I hope this is enough relaying goodness for everyone. Source code will probably materialise at some stage, public logs are a possibility but I think Deaygo plans to have the official ones available soon.

**Comment by draykhar** [comment]
Reopen, as these relays are currently broken?

**Comment by edk0** [comment]
They're fixed again, sorry about that.
