### ISSUE TITLE
Resolve issues with CH, warps, and homes

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#28]
Homes and warps have been disappearing on a fairly regular basis across all three servers.  P lost its warps within the past 5 days, S also did within a similar timeframe (and I believe also lost homes, I've heard Zitkovich comment on it).  C lost its homes at some point in the past couple of days as well.

As I understand it, this is likely related to issues with CommandHelper.  We've been trying a bunch of dev builds recently, but the recent attempts have causing significant server lag.  (Particularly bad case on C this weekend, though it's not confirmed what exact conditions led to that lag or even whether CH was involved at all.)  I think we've had to revert to old builds in most cases.

**Comment by ghost** [comment]
I thought I added this to here, apparently not.

Fix has been written, waiting on @Deaygo's approval: https://github.com/NerdNu/TPControl/pull/8

**Comment by LadyCailin** [comment]
This should be fixed in CH now, and C is up to date on the latest version, and the database should be back up to speed with all the warps and homes that were in use previously. P and S will follow.

**Comment by ludeman84** [comment]
C was having persistence issues again this morning, and c45y was hesitant to revert it because of some database changes, I think.  May want to look into it when you have a chance, thanks!

**Comment by stevommmm** [comment]
CH is fixed.
