### ISSUE TITLE
Block beds from changing spawn upon both death and leaving end

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#29]
We successfully blocked beds from changing spawn points upon death for a long time.  However, by sleeping in a bed, you change the location to which you respawn upon exiting the End, and this wasn't being blocked.  This spawnpoint appears to be buried within the player data, as it persists even if the bed is broken.  In fact, even with beds being banned on S right now, I believe players who used a bed to change their leaving-End spawnpoint before they were banned still go there - and as far as I know we haven't figured out a way to clear that.

If we can block both, we should be able to unban beds, since we're blocking their placement in the nether and End already.

**Comment by stevommmm** [comment]
Not sure what is going on here. NerdSpawn takes beds into account and should be setting the spawn point accordingly.

https://github.com/NerdNu/NerdSpawn/blob/master/src/nu/nerd/nerdspawn/NerdSpawnListener.java#L42

**Comment by ghost** [comment]
https://github.com/NerdNu/NerdSpawn/pull/3

Tested and working on my local server.

**Comment by stevommmm** [comment]
Currently running on S. As far as I have been notified this issue is resolved.

Unbanned beds in end and nether.

**Comment by ludeman84** [comment]
Reopening because beds are still banned on S - did something change that forced us to ban them again, or did we just never unban them in the first place?

**Comment by ghost** [comment]
They seemed to be briefly unbanned before being banned again for this revision.

**Comment by ghost** [comment]
Is this still an issue?

**Comment by totemo** [comment]
As far as I know, beds are banned on S because of bed-spawn camping, not because of any bug in the way that beds work.  The code in https://github.com/NerdNu/NerdSpawn/blob/master/src/nu/nerd/nerdspawn/NerdSpawnListener.java for onPlayerRespawn() and onPlayerPortal() (returning from the end) looks correct to me.  In any case, the issue is not relevant to S until or unless the S admins change the policy on using beds there.
