### ISSUE TITLE
[Request] Change Log Length

### ISSUE THREAD

**Issue by nsh22** [NerdNu/NerdBugs#3]
Hello!
I am finding that many modreqs for grief go unresolved/unfixed because a lot of the grief may be too old for the logs to show. If the resources can easily accommodate for it would it be possible to extend the time the logs are kept to up to one month?

**Comment by ghost** [comment]
Hey buddy,
I started a thread up on the forums about this quite a while ago now. Check it out.

http://nerd.nu/forum/index.php?p=/discussion/9864/logs/p1

**Comment by barneygale** [comment]
I'll page deaygo about this

**Comment by ludeman84** [comment]
We've actually been running on 28-day logs for quite some time, for everything except stone, dirt, gravel, and sand.  I have a proposal regarding that, but this specific issue has been resolved for some time.
