### ISSUE TITLE
Block portal lighting from flint and steel

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#31]
Given that fire spread/damage is already turned off, if we can successfully block the ability of flint and steel to light portals (and verify it in testing), I don't think there's any reason we'd need to keep flint and steel banned on S and P. This would allow players to light their own fires, though we'd obviously need to clear it with S and P admins first.

**Comment by stevommmm** [comment]
Pulled code is active on C,P,S.

A singular portal block is still created even with the event canceled.

Needs to remove the block, easy to do and I'll add it in tomorrow if nobody beats me to it

**Comment by NinjaWolf** [comment]
Couldn't recreate the single portal block issue, ill leave it to c4.

**Comment by ghost** [comment]
Also couldn't reproduce the single portal block issue, are you sure it's not clientside, c45y?

**Comment by stevommmm** [comment]
http://imgur.com/a/Szp4M

I will have to test at another time, this shouldn't be happening, and doesn't on my local dev server ( but does on P )

**Comment by NinjaWolf** [comment]
Hmm. Very Strange. I mean off the top of my head, maybe loop thru the blocks right next to the portal block and if its a portal block, set to air.

**Comment by stevommmm** [comment]
Fixed and tested with: https://github.com/NerdNu/KitchenSink/commit/1bd0388b494aca6694c3db7d9a81aad330d861a5

Pushing to servers.
