### ISSUE TITLE
Update terrain.png on cartos

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#33]
[AlcoJew mentioned this needed to be done](http://www.reddit.com/r/mcpublic/comments/ys2r3/pve_carto_is_up_for_real_this_time/c5yccyu?context=1) to fix the carto rendering issue, see [the roof of Ooer's mansion](http://redditpublic.com/carto/pve/current/index.html#/-435/64/1138/-1/0/0) ([screenshot for posterity](http://i.imgur.com/G6YtX.jpg)) where the some of new stairs were used for a good example.

**Comment by stevommmm** [comment]
Updated, we will see if it works next time the cartos run, ill check on it in a few days

**Comment by joealcorn** [comment]
Seems to be fixed!
