### ISSUE TITLE
Add ore-mining to PlumpXP

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#34]
I believe NinjaW0lf has a fork of PlumpXP which adds a config option to plump experience dropped from ore-mining:
https://github.com/NinjaWolf/PlumpXP

I think c45y may have looked at this before.

I figure this would be fine for S, since we already plump mob kills, but I cleared it with dan1son to be safe.  Could also come in handy if we ever want to use it on other servers.

**Comment by ludeman84** [comment]
Also worth noting, from NinjaW0lf:

I'm still waiting on bukkit to add the method to set Exp to drop from furnace. There is a pull request on bukkits git which would do exactly this, adds an event fired when u click an item out of a furnace, since we don't have one. Once I have that I can add this to plumpxp.

Here a link to the bukkit pr.
https://github.com/Bukkit/CraftBukkit/pull/888

Once that gets pulled, or bukkit adds it themselves, I can add furnace xp buff.

**Comment by stevommmm** [comment]
Forked to NerdNu repo, pinged @Deaygo to set it up in jenkins.

We'll push to nerd once its all done and a little testing happens

**Comment by ludeman84** [comment]
Note that as of 1.4.2, there is also XP awarded for breeding and fishing.  I'm also pretty sure the buff on mining was not in place during the temp chaos map, though I'm not sure if we ever actually pushed that.

It'd also be nice to be able to have players drop a much larger percentage of their experience when killed, especially from PVP.

All that said, since we're not using this plugin anymore, I'm going to go ahead and close this; but if we decide to use it again in the future, keep in mind the other sources of XP that are out there now.
