### ISSUE TITLE
Carto not updating on P

### ISSUE THREAD

**Issue by djdisturbed** [NerdNu/NerdBugs#35]
just noticed that the carto has not updated in like 4 or 5 days (or more)

**Comment by ludeman84** [comment]
It did update on Oct-10, but it has not updated since.  Are we still manually running cartos atm?

**Comment by stevommmm** [comment]
The manual running of ~schedule-carto kicks off and runs properly. Just looks like the code to determine to make one or not somehow broke. 

Narrowed down the process to the wrapper

**Comment by ludeman84** [comment]
P seems to be updated okay (assuming you're not updating it manually), but C is still stuck back on October 10, at the moment.

**Comment by djdisturbed** [comment]
One of the admins manually updated P last night, He said he was going to work on the issue last night as well, dunno if he did

**Comment by slide23** [comment]
Fixed now!

**Comment by ludeman84** [comment]
Both are updating as of last night, awesome.  Closing, just bug me or a tech if it happens again.
