### ISSUE TITLE
Sign text no longer stored in LB on S

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#36]
As of the new S rev, it looks like the LogBlock database is no longer storing sign text data. As a result, sign text cannot be rolled back, i.e. the way it used to be back in the day.  Did we switch to a different build?  I know it's really frustrating for players to have to remember all the text on their signs.

I just confirmed that this is a problem on S, but not on P or C.

**Comment by stevommmm** [comment]
Fixed, copied the world.yml across from the old S config
