### ISSUE TITLE
You can /give items to other players on Creative

### ISSUE THREAD

**Issue by barneygale** [NerdNu/NerdBugs#37]
Hey, I just confirmed with Barlimore that /give isn't properly restricted on creative mode, meaning you can /give other players items, up to a limit of 512. This has some potential for inventory spamming.

/give is in there for a reason: it means people using TooManyItems can use it without any tweaks on the nerd server. For this reason, the command _should_ work if the username matches the player issuing the command, OR if the player running is a mod

Here's a patch:

<pre>
*:/give $player $ = >>>
    _assertperm('restricted', 1)
    assign(@a, _parseiargs($))
    if(equals(@a, null),
        msg(concat(color(gray), 'Usage: /give <player> <itemid>[:metadata] [quantity]')),
    #else:
        if(or(equals($player, player()), has_permission('nerdch.level.restricted')),
            try(
                pgive_item(_getonlinename($player), concat(@a[0], ':', @a[1]), @a[2])
                msg(concat(color(gray), 'Giving ', @a[2], ' of ', data_name(@a[0]), ' to ', $player)),
            @e,
                msg(concat(color(red), 'Player not found!'))),
        #else:
            msg(concat(color(red), 'You cannot give items to other players!'))))
<<<

</pre>

**Comment by ghost** [comment]
Confirmed that this is actually an issue. Doesn't work for ModMode however, so this isn't a concern.

**Comment by stevommmm** [comment]
There is no real need for this functionality, overwritten to give the player running /give items regardless.

Thanks for the heads up

**Comment by barneygale** [comment]
I thought it'd be handy for, say, giving out arena prizes or in other edge-cases.
