### ISSUE TITLE
Send notifications to player and other mods when a player is muted or unmuted

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#39]
Back in the day, we had just the /mute command; /mute (playername) toggled whether a player was muted or unmuted.  When the command was performed, a mod-broadcast message was sent of the form (or similar to) "[Mod broadcast - ludeman84] RandomUser has been muted/unmuted."

Since then, we've switched to separate /mute and /unmute commands, which I think is a good thing - the downside of the toggle is that two users trying to mute the same person ends up with them just being unmuted again.  However, the notification for other mods was always really useful, and I'd like to bring that back (as well as a notification for the user getting muted/unmuted, so they know it has changed without the mod having to say so directly).  As it stands now, I generally have to manually type in a /mb to let other mods know that I've muted someone.

So, the proposed changes:
1. If a player was unmuted, and a mod runs /mute:
      a. Send a notification to the player which states they are now muted.
      b. Send a mod broadcast on behalf of that mod stating that said player was muted.
2. If a player was muted, and a mode runs /unmute:
      a. Send a notification to the player which states they are now unmuted.
      b. Send a mod broadcast on behalf of that mod stating that said player was unmuted.

A simpler version of this would be to just do (a) and (b) every time, regardless of whether the user's mute status actually changed.

**Comment by stevommmm** [comment]
https://github.com/stevommmm/LolNo/commit/12b0214992812eef9ce79eca35d4384b23b4845b

**Comment by stevommmm** [comment]
Running on all 3.
