### ISSUE TITLE
Enable player radar on P

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#40]
This was discussed here:
http://nerd.nu/forum/index.php?p=/discussion/17138/player-radars-on-c-and-p#Item_7

The P admins are on board with this, and it sounds like the technical implementation is (allegedly) easy,  it's all handled through Rei's Minimap and NC+.  In that thread, bencvt details the changes that need to be made.

Would be really nice if we could get this going for 1.4.1.

**Comment by slide23** [comment]
NC+ currently only lets you enable everything. I've submitted a patch that allows using a permission for each radar type.

**Comment by ludeman84** [comment]
Bumping. What are the chances we can have this enabled for the new rev? This is a very highly-requested feature and it's unclear to me how much work needs to be done.

**Comment by jcll** [comment]
Was pulled in. We just need to bump the build and add "nocheatplus.mods.rei.radar.player" to the perm file for everyone.

**Comment by ludeman84** [comment]
Thanks, guys.
http://www.reddit.com/r/mcpublic/comments/1983lm/player_radar_on_p/
