### ISSUE TITLE
/enchant doesn't work with bows

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#41]
This was tested on all 3 servers.

If you try to add any bow enchantment with the (as far as I can tell) correct names, you get this error:
http://i.imgur.com/yhGun.png

This is also the error you get if, for example, you try to run "/enchant sillyname 3" on a diamond sword, or something. Basically, it seems to imply that you've tried to add an enchantment that doesn't exist.

For comparison, if you run "/enchant sharpness 99" on a diamond sword, you get this error:
http://i.imgur.com/kM2x4.png

Is it possible we just never loaded bow enchantments into this function?

**Comment by LadyCailin** [comment]
This appears to work now. I didn't change anything, so I would assume the bukkit bug was the cause of this.

**Comment by ludeman84** [comment]
Are you sure? I tried this on S just now and still couldn't get it to work.

Can you give me an example command to try?

**Comment by ludeman84** [comment]
This is now working - thanks LadyCailin!
