### ISSUE TITLE
Create nerd.nu e-mails for admin groups

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#42]
Suggested by wickedcoolsteve, would be a very handy alternative way for users to get in touch with each group of admins.  (As it stands now, they have to go look up the admins on nerd.nu/staff, and individually message them on Reddit or find their names on the forum.)

Would be 5 groups - Cadmins, Padmins, Sadmins, headadmins, techadmins - and presumably would be opt-in for all admins as far as whether they wanted to participate or not.

**Comment by ghost** [comment]
Would it be better/more intuitive to use creative/pve/survival for the per-server admins, as opposed to "padmins" etc.?

**Comment by jcll** [comment]
I had thought we where going for a global admins@nerd.nu address. And have a opt-in with who gets the emails.

**Comment by ludeman84** [comment]
jcll - that would be fine, too.

**Comment by jcll** [comment]
We have a admins@nerd.nu email now.
