### ISSUE TITLE
Update carto software for 1.3/1.4 textures

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#43]
Last I checked, our cartograph software was not updated to include the textures from either the 1.3 or 1.4 patches, which means that any blocks using those textures appear transparent in our current cartographs.

We need to update our cartography software to use the latest terrain.png so all the new block types show up on the cartograph - would be nice to do this before the first P rev10 cartograph goes out (roughly a week from now, or so).

**Comment by slide23** [comment]
Updated!
