### ISSUE TITLE
Create user interface for parsing mob-kill logs

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#45]
This does not require a tech admin to do it, anyone who's willing can help with this.

On the PvE server, we log kills of all farm animals, in the following format:

<username>|<mob type>|<realm>|<x-coordinate>|<y-coordinate>|<z-coordinate>| C[<chunk x-coordinate>,<chunk z-coodinate>]

Here's what a typical sampling of logs for this looks like (names removed):

2012-11-10 20:25:47 [INFO] [KitchenSink] [MobKill] UsernameA|COW|world|1184.0304431033346|50.0|-1178.1175739333112| C[74,-74]
012-11-10 20:27:47 [INFO] [KitchenSink] [MobKill] UsernameB|CHICKEN|world|706.3859506395391|75.0|553.5975846579629| C[44,34]
2012-11-10 20:30:41 [INFO] [KitchenSink] [MobKill] UsernameC|CHICKEN|world|-1274.499516037404|78.0|823.5260278803062| C[-80,51]
2012-11-10 20:40:31 [INFO] [KitchenSink] [MobKill] UsernameD|VILLAGER|world|-282.07499998807907|100.0|-1554.4831071398835| C[-18,-98]

We have experimented with various degrees of rolling back mobs for users on the P server - previously any claimed mobs, now only those mobs in clearly locked and protected pens.  Part of the challenge here is that to roll back mobs, we need proof they were killed in the logs - and attempting to parse logs of the format above is unbelievably difficult.  You'd have to guess the coordinates of where they were killed, then start searching random strings with those coordinates until you might get lucky.

What we're looking for is some kind of user interface (IRC bot? GUI? etc.) that could take a stream of these log entries and parse them in a much more accessible way.  At minimum, it would return a list of mob kill entries that meet some criteria, potentially even plot them on a map.  Examples of said criteria:
-> Only include certain times of mob
-> Only include kills within R distance of (x,y,z)
-> Only include kills before time X, after time Y, or both
-> Only include kills by player P
-> Only include kills in the chunks {...}
-> etc.

**Comment by forty-two** [comment]
I've stuck together an IRC bot to attempt this, it's up at https://github.com/forty-two/MobBot

It currently runs by reading a log file (fairly easily changed) and can do searches of all the criteria above.

Attempting to think of ways to make more useful output, but the current format is still better than reading log files :P

**Comment by slide23** [comment]
Implemented in Logblock now, see LogBlock/LogBlock@c0255b855b7d3abf9a19194ef8200dabcef9e54e

Added commands 'kills' and params 'killer' and 'victim'

Examples: 

/lb kills - Lists all kills 
/lb kills coords - Lists all kills with coords 
/lb kills sel - Lists all kills in an area 
/lb kills area 20 - lists all kills within 20 blocks 
/lb kills player slide23 - lists all kills and deaths by slide23 
/lb kills killer slide23 - lists only kills by slide23 
/lb kills victim slide23 - lists only deaths by slide23 
/lb kills sum p - lists kills and deaths as totals per player 
/lb kills sel sum p - lists kills and deaths as totals per player within the area 
/lb kills area 20 sum p - lists kills and deaths as totals per player within 20 blocks 
/lb kills sum p player slide23 - lists kills and deaths as totals for only slide23 
/lb kills sum p killer slide23 - lists only kills as totals for only slide23
