### ISSUE TITLE
Add alias /furnace-top for C

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#46]
Even though creative mode has had insta-break for a year now, for whatever reason furnaces are still a preferred block of choice for griefers on C to blockspam with.  Because of this, we still have WorldGuard warnings go off anytime a furnace is placed - which is helpful to catch some griefers, but really annoying when they're being used by legitimate builders and spamming the heck out of mods' chat windows.

What I'm proposing is to create a simple alias for quickly checking who's placed the most furnaces over a given time interval.  By making this simple to use, we can still identify griefers using furnances, and potentially be able to get rid of the WG warnings.

Proposal:
/furnace-top (time) = /lb block 61 sum players time (time)

**Comment by Dumbo52** [comment]
Addressed [here](http://github.com/NerdNu/nerdCH/pull/4).
