### ISSUE TITLE
Web interface for non-techadmins to view/modify server messages

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#49]
By server messages, I'm referring to the periodic [Server] messages in purple that appear every 5 minutes or so, saying things like (for example)

[Server] Issues with the servers or staff? Please talk to a server, tech or head admin

Recent feedback this fall has suggested that players really appreciate us keeping these [Server] messages up-to-date with the latest revision news, policy changes, and feedback threads.  Problem is, this requires a tech admin each time to either retrieve the current list of messages (to find and remove outdated ones), or to modify the list.  For example, I know there's still a [Server] message on S with a URL asking users to give feedback on...last revision.  This is tedious work for the tech admins, and slows down our ability to keep these messages up-to-date.

Would it be possible to create a simple plaintext website which lists the current rotation of [Server] messages on each of the three servers?  With that, tech admin interaction would only be necessary to modify messages, not view the list.  And given the randomness at which [Server] messages appear on each server, it's much easier to keep the messages up-to-date if they're all listed in one place for easy viewing.

Could we potentially go one step further and create a web interface for non-tech admins (presumably other admins) to actually modify the [Server] message list?  Given that this could require some kind of authentication, I imagine this is kind of a longshot, but figured I'd ask.

**Comment by jcll** [comment]
I think this may not be a good idea. Since it does somewhat blur the line between head and tech. Mainly the policy vs server change aspect.

**Comment by ludeman84** [comment]
In that case, can we at least make a viewable page?

**Comment by LadyCailin** [comment]
I have something set up to view them now, talk to me in a private channel, and I'll show you how to access them :)
