### ISSUE TITLE
Give admins ability to create stacks of potions

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#50]
This seems awfully specific, but it's extremely useful for things like arenas and quests - in particular, loading up dispensers with 9 stacks of potions.

Option 1: Make commands of the form "/i 373:8201 64" actually create 64-stacks of potions
Option 2: Allow commands of the form "/give ludeman84 373 64 8201" - this works in vanilla, but has been blocked to return simply "nope"

Is this feasible?

**Comment by barneygale** [comment]
I'm not sure why 'give' is returning 'nope' - according to [NerdBug 37](https://github.com/NerdNu/NerdBugs/issues/37) c4 patched it to only ever give to the player running the command.

What's the current behaviour of "/i 373:8201 64"? It gives only one potion, or it gives 64 but not condensed into a stack?

**Comment by LadyCailin** [comment]
Ok, I've fixed this by adding /fill [$qty=64]. It will set the quantity of the currently held item to $qty, regardless of whether or not that item will normally stack. So, just give yourself one of the item, then /fill. Admin only.
