### ISSUE TITLE
Create simple command for creating player skulls

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#51]
/skull [username]

Admin command which inserts a skull block into the user's inventory, with the skull belonging to the skin of [username].  Per the Minecraft wiki, this can be done as follows:

"Player heads do not/will not drop in vanilla, but mapmakers/modders/etc. can make them by adding an NBT string tag "SkullOwner" -> (player name) on the skull items."

Users have expressed interest in these types of skulls being available in some form on the server:
http://www.reddit.com/r/mcpublic/comments/12f8ty/can_we_get_this/
http://dev.bukkit.org/server-mods/player-heads/
Whether we want to incorporate skulls in those kinds of ways is a topic for future debate, but just having a simple interface to create skulls of given users would surely be fun and handy - recognition of particular users for their achievements (perhaps as part of a spawn monument?), arena prizes, staff boards, etc.

Probably not worth the trouble if it can't be done within an existing plugin.

**Comment by ghost** [comment]
In theory, it can be done very easily (and can be expanded to allow easy modding of spawners). Will work on if slide23 is busy.

**Comment by Deaygo** [comment]
What you might want to do is see if @wraithguard01 would be willing to add support for it into CommandHelper.

**Comment by ludeman84** [comment]
Deaygo, yeah, that's exactly what I had in mind when speculating last night.

**Comment by ludeman84** [comment]
Bumping - is this something we could potentially have as a standalone command, perhaps in time for the next S revision?  Would have a hugely beneficial impact for stuff like arenas and other server events. :)

**Comment by LadyCailin** [comment]
K, /skull $player :)
