### ISSUE TITLE
Log player drops upon death

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#52]
This was requested by a player, but could be useful in general in investigating a variety of situations.

Would it be possible to write the contents of a player's inventory to log upon death, without (1) disrupting the server, (2) disrupting the player's client (while it writes to log as the player dies), or (3) significantly increasing the size of the logs?

**Comment by stevommmm** [comment]
https://github.com/NerdNu/KitchenSink/commit/9b4207b289aac4063ce7c7f09b4e2c2f4c47fec5

**Comment by stevommmm** [comment]
Pushed to nerd.

Enabled on S currently

**Comment by ludeman84** [comment]
Been running on S successfully for a while via KitchenSink - I _imagine_ it can be added to P at the P admins' request without too much trouble.
