### ISSUE TITLE
Bring back chaos server

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#54]
Things to consider:
-> How is our main server load? CPU usage? How does it look at peak, especially after a new patch? Would there be room for such a server on our main box, especially given that we often have an auxiliary server set up for special events and/or new revision setup?
-> What are alternatives to this?

Not expecting an immediate resolution to this by any stretch, just wanted us to keep it in mind.

**Comment by slide23** [comment]
It's up! :D
