### ISSUE TITLE
Generalized command for teleporting players to a warp

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#55]
Proposed command:
/warpto (player) (warp)

Prerequisites:
-> User (player) has to be online.
-> Warp (warp) has to exist.
-> Command issuer must be a mod or admin.

Effect:
Essentially performs the following commands for the user who issues it, in sequence:
- /sethome
- /warp (warp)
- /tphere (player)
- /home

The net effect is that it moves the specified user to the designated warp location.  This would be a generalization of the "/jail" command which I believe has been around for some time.  Not sure if there a more straightforward way to do this than the commands I listed above.

Benefits:
-> Expands the functionality of /jail to consider any potential warp.
-> Greatly simplifies the operation of arenas on Survival (and similar events), by allowing a single staff member to move players around (into the arena, into the arena boxes, off the arena floor, etc.) simply via text command.  A single staff member could run an arena event without too much trouble by having access to this command.

**Comment by Dumbo52** [comment]
I just addressed this feature proposal [here](http://github.com/NerdNu/nerdCH/pull/4).
The command _warpto <player> <warp>_, callable by moderators, teleports the player to the specified warp.
