### ISSUE TITLE
Get /warpto on P and S, etc.

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#56]
Long story short, dumbo52 made this pull request to address a couple other tickets:
https://github.com/NerdNu/nerdCH/pull/4

I believe this is running on C, though /furnace-top seems to not be working.  However, /warpto does not work on S or P.  Given that much of its value is use by mods there (for example, moving players into boxes during S arena events), can we get that patch going on the other servers?  Thanks!

**Comment by LadyCailin** [comment]
Added!
