### ISSUE TITLE
Unban item frames

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#57]
Can we determine whether the issues that caused us to ban item frames in the first place have been resolved, and if so, unban item frames on the servers?

**Comment by ludeman84** [comment]
Current approach is to try to block map placement inside item frames (which are known to still be a major source of client lag) so that we can unban frames in general.  Thread:
http://nerd.nu/forum/index.php?p=/discussion/18281/attempt-to-get-item-frames-back-item-frames-at-the-cost-of-mapss#Item_5

**Comment by LadyCailin** [comment]
Fixed ^_^
