### ISSUE TITLE
Carto snapshots daily (or every 2 days)

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#58]
Idea here:
http://www.reddit.com/r/mcpublic/comments/15cywf/carto_done_on_first_few_days_of_rev/

It's been proposed before.  I believe the key points are:
1. Keep the cartos generating all the time, even if the carto is "hidden" (i.e. P during first two weeks of a new rev)
2. Take a snapshot of every carto each time it is generated, and keep a public folder of those snapshots somewhere

**Comment by ludeman84** [comment]
Bumping - would it be possible to keep the P cartos running in a hidden location during the first two weeks of the new rev, so that we can have snapshots for the full length of the rev available?

How difficult would it be to automatically take a high-res image of the full map anytime a new carto is made?

Would there be major server impact if cartos were generated daily instead of every 2 days?

Thanks!

**Comment by ludeman84** [comment]
Bumping; it'd be really nice to have something like this ready to go for at least the beginning of the new P revision.

**Comment by slide23** [comment]
Done. [PvE](http://redditpublic.com/carto/pve/current/static/) [Creative](http://redditpublic.com/carto/creative/current/static/)
