### ISSUE TITLE
Consider plugin for making invisibility wear off in PVP

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#61]
Relevant thread (it's a fork of KitchenSink):
http://www.reddit.com/r/mcpublic/comments/167i1m/survival_revision_20_will_go_live_this_friday/c7uc9lf?context=3

2 of the S admins (Bestor and dan1son) have signed off on wanting to incorporate it onto S so far.

**Comment by ludeman84** [comment]
Updates on this:

-Was mentioned here:
http://www.reddit.com/r/mcpublic/comments/1btgec/all_about_survival_rev21_part_2_upcoming_features/

-After mentioning it there, pull request was offered for the other half of the proposed setup (see Thundaklap above - thanks!)

-Another suggestion we might want to consider in conjunction with these:
http://www.reddit.com/r/mcpublic/comments/1bxrqw/suggestion_night_vision_potions_allow_you_to_see/

**Comment by ludeman84** [comment]
Another option, which could be used as a stop-gap for the above suggestion, would be to use the 1.5 scoreboard API to add everyone on the server to the same "team" by default, then enable a specific setting that allows you to see invisible team members.  This would render invis pots effectively useless, but it would allow use to re-enable brewing with golden carrots in general (because that is blocked right now, users are unable to create night vision potions).

This was suggested by gsand, who said he has seen this used on other servers.

**Comment by Tharine** [comment]
What's holding us back from implementing any of this, if anyone knows? We've been waiting for invisibility potions to be enabled for quite some time now, and we haven't seen any progress made on this since smiler100 provided the latest pull request.

**Comment by LadyCailin** [comment]
The merged in code did not work @Thundaklap

**Comment by LadyCailin** [comment]
Just kidding, I derped! Thanks!
