### ISSUE TITLE
Fix /unmute

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#62]
/unmute says to the staff that the player is unmuted and the player gets the message they're unmuted, but they still cannot talk in chat. So the issue is that they can be brought into a muted state, but can't be brought out. As far as either the staff and player can tell, it worked. Until the player tries typing, then they still get the message something like "A staff memeber has muted you, please /modreq to be unmuted"

**Comment by ghost** [comment]
I believe this issue may have been resolved now through C45y's efforts.

Jcll confirmed this here:
http://nerd.nu/forum/index.php?p=/discussion/18471/redundant-dont-mute#Item_4

**Comment by LadyCailin** [comment]
Fixed!
