### ISSUE TITLE
On restart, items being placed into inv. get deleted

### ISSUE THREAD

**Issue by TeGrem** [NerdNu/NerdBugs#63]
If you're holding an item with your mouse(like, your moving a stack of stuff) and the server restarts, it will be deleted. I lost roughly 13 diamonds in this way.

**Comment by LadyCailin** [comment]
This is not an issue with our server specifically, you'll have to take this up with bukkit/mojang for a fix. Regardless, there is the 60 second server restart message, so it's usually not a surprise when the server restarts.
