### ISSUE TITLE
Potion effects stay when leaving ModMode

### ISSUE THREAD

**Issue by timovv** [NerdNu/NerdBugs#64]
I accidentally found this out by using a night vision potion on S while looking at a modreq so I could see in the dark. When I left modmode, the potion effect transferred onto my normal player.

**Comment by tompreuss** [comment]
Happened to me too, I just make sure to drink some milk before leaving modmode to fix it.

**Comment by Dumbo52** [comment]
Addressed [here](https://github.com/NerdNu/ModMode/pull/3).

**Comment by LadyCailin** [comment]
Pulled and deployed to the server. Thanks @Dumbo52!
