### ISSUE TITLE
Minecarts disappear even when occupied

### ISSUE THREAD

**Issue by zkatancik** [NerdNu/NerdBugs#65]
We have a cow system that uses minecarts to breed them. The cows sit in the minecarts. After logging off for a few hours, the cows are running free and the minecart is gone! This happens if the minecarts are stationary or constantly moving.

**Comment by NinjaWolf** [comment]
Pretty sure that is a bug that Moby needs to fix.

**Comment by zkatancik** [comment]
http://www.reddit.com/r/mcpublic/comments/175vhz/the_minecart_cow_problem/

**Comment by ludeman84** [comment]
Was able to reproduce this on P; however, it is my understanding that this is an issue with the vanilla game, rather than anything we're doing locally (via our plugins) with mobs or minecarts.  I'd recommend reporting it to Mojang.
