### ISSUE TITLE
Modmode flying not working upon first login.

### ISSUE THREAD

**Issue by ghost** [NerdNu/NerdBugs#66]
When entering modmode for the first time upon survival (only), flying is disabled. Only upon re-entering modmode will flying be enabled.

This is not replicated upon entering modmode upon all occasions from what I've experienced.

**Comment by totemo** [comment]
The ModMode code has undergone more-or-less a complete (and hopefully final) rewrite for 1.6.2.  I haven't been able to duplicate this issue with that new code. Closing.
