### ISSUE TITLE
Fix /unenchant Wrt Books

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#67]
Using /unenchant on an enchanted book will remove ALL enchanted books with the same enchantment from your inventory, and replace them with a single unenchanted book.  Fix /unenchant to apply only to the book that you are holding.

**Comment by NinjaWolf** [comment]
Fixed:

Now with 10% less bugs!
https://github.com/NerdNu/KitchenSink/pull/15

**Comment by LadyCailin** [comment]
Fixed.
