### ISSUE TITLE
/xray-rb still broken

### ISSUE THREAD

**Issue by totemo** [NerdNu/NerdBugs#70]
And has been going back to, at the latest, August of last year:

http://nerd.nu/forum/index.php?p=/discussion/comment/58431#Comment_58431
http://nerd.nu/forum/index.php?p=/discussion/comment/60285#Comment_60285

I can't find the CommandHelper code in https://github.com/NerdNu to see what it is doing exactly, but I assume it is naively issuing two LogBlock commands in sequence:

/lb rollback player $p time $t
/lb redo player $p time $t destroyed block 56

The problem with that is that they run asynchronously and more often that not the second command takes WAY less time to finish.  So they end up being executed in the opposite order.

The default rollback duration is apparently 21 days on P and 28 days on S, so the following code will need some tweaking (it's also untested and my first CH script), but can we do something like this:

*:/xray-rb $p [$time=21] = >>>
    /lb rollback player $p time $time days world "world"
    set_timeout(10 \* 1000,closure(run(/lb redo player $p destroyed block 56 time $time days world "world"))) 
<<<

**Comment by LadyCailin** [comment]
Done :) Let me know if it actually works. Btw, here's what it looks like:

``` php
*:/'xray-rb' $ = >>>
        _assertperm('mod', 0)
        call_alias('/lbrb '.$)
        set_timeout(10 * 1000, closure(
                run('/lb redo destroyed block 56 player '.$.' since 28 days')
        ))
<<<
```

**Comment by totemo** [comment]
Works fine on S.  Fails on P because the time limit on rollbacks and redos is 21 days.  Also TIL that /lbrb only does 2 weeks worth of edits.  

Maybe switch to 21 days for the redo?

![2013-03-08_02 47 47-CerpinCygnus](https://f.cloud.github.com/assets/1934688/232916/781aa4dc-8744-11e2-9dd0-e4aec1c17bd7.png)

**Comment by LadyCailin** [comment]
Ok, fixed ^_^
