### ISSUE TITLE
Head in a solid block prevents interacting with world

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#72]
So, I've noticed lately that having one's head inside a solid block (transparency is irrelevant) prevents one from interacting with the world. I've noticed in chat that this phenomenon happens to others as well. I personally had to be rescued from the same position on two occasions because I ran out of enderpearls, and I started with **well over 100 pearls**. If I were to recreate these symptoms, I would use commandhelper script along the lines of

bind(player_interact,null,null,@event,if(head_is_in_solid_block(@event[player]),cancel()))

People have reported problems with a wide range of interactions, including pearls and breaking leaves that their head is stuck in _in their own permissions region_, and we would all appreciate expeditious attention to this matter. Thank you for your time and for all that you do.

**Comment by zifnab06** [comment]
I realize this is fairly old: is it still an issue? And, is it an issue in vanilla minecraft or is one of Nerds plugins causing it?

**Comment by mattman00000** [comment]
I haven't noticed it happening lately, I think I recall looking into it a bit at some point and noticing that NCP added an option about it or something, but I don't recall.

For PvE, the issue is no longer an issue. I'll go ahead and close it.
