### ISSUE TITLE
Update carto software for 1.5 textures

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#74]
Same issue as this one was, but for 1.5 textures:
https://github.com/NerdNu/NerdBugs/issues/43

Textures like quartz are rendered as invisible. For example, I'm told this building is supposed to be white on the server:
http://redditpublic.com/carto/creative/current/index.html#/-320/64/-341/-1/0/0

**Comment by slide23** [comment]
Done!
