### ISSUE TITLE
Tools break after one use in survival mode on C

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#75]
http://www.reddit.com/r/mcpublic/comments/1awbc0/creative_has_updated_to_151/c91c2k8

I just confirmed that it's still happening, by spawning some diamond shovels and trying to dig up grass (they disappear after one use).

**Comment by slide23** [comment]
Bug in WorldGuard, waiting for update.

**Comment by FourDown** [comment]
Is this still happening? If not could a tech close this, thanks.

**Comment by ghost** [comment]
Re-iterating a message from GMMan as there is a new version of world guard available that fixes this issue.

http://dev.bukkit.org/bukkit-plugins/worldguard/files/36-world-guard-5-7-5/

**Comment by totemo** [comment]
Installed WorldGuard 5.7.5. Confirmed fixed in creative and survival modes.
