### ISSUE TITLE
MobLimiter doesn't speed up growth of chickens from eggs

### ISSUE THREAD

**Issue by jsojl** [NerdNu/NerdBugs#78]
Hi all, thanks so much for all the work you guys do making the nerd.nu server such a great place to play.  I've really enjoyed it.  During testing on the chaos server I noticed that baby chickens made from thrown eggs don't get the sped up growth that baby chickens from breeding do.  Is this intentional?  I'm asking because now that we can actually collect eggs using hoppers, throwing eggs is also a great way to get more chickens and it'd be great if these chickens could grow quickly too, since they too will be culled when the chunk unloads, so it seems like a good balance.  Thanks for your consideration, and take care.

-jsojl

**Comment by ludeman84** [comment]
I was able to reproduce this on P, even compensating for the low tick rate at present.  Mob culling on chunk unload, mob drop plumping, and breeding speed-up for all other types of breeding have been tested to be working fine, so this might just be isolated to us not including the egg-hatching event.

**Comment by slide23** [comment]
Fixed: NerdNu/MobLimiter@39dfaf69ae4c18ce7868d704a86e15c8d9d6d6a4
