### ISSUE TITLE
/xray-rb still broken on P

### ISSUE THREAD

**Issue by totemo** [NerdNu/NerdBugs#80]
It's broken again/still.  The ores stay where they are after the first rollback.  Based on the output that comes back to the client, it appears that the /lb redo to remove diamond ore is never performed.  Is /xray-rb an alias of /lbrb?

To verify resolution:

/xray-rb logfromblammo

**Comment by FourDown** [comment]
Unless the script has been edited at all, this is what is should be:

http://pastebin.com/raw.php?i=mv2iSSsm

Hope that helps.

**Comment by totemo** [comment]
*:/'xray-rb' $ = >>>
    _assertperm('mod', 0)
    call_alias(concat('/lbrb ', $))
    run(concat('/lb redo destroyed block 56 player ', $, ' since 28 days'))
<<<

Yep.  Well, that shows the problem, at least.  The LogBlock commands run asynchronously and typically complete out of order.  The redo is quick and finishes first, removing dimmins that don't exist.  The full rollback (/lbrb) might take anything up to 45 seconds for 30k blocks or so and puts all the dimmins back.

**Comment by totemo** [comment]
Fixed. PVE is now running the Survival version of this code, and that has been made more reliable for large rollbacks.
