### ISSUE TITLE
Add /ignore command

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#87]
Planned feature for new S rev, proposed in user feedback and approved by S admins:
http://www.reddit.com/r/mcpublic/comments/1btgec/all_about_survival_rev21_part_2_upcoming_features/
Could potentially use on other servers.

Main idea would be to give players the ability to block chat, clan chat, and/or messages from specific players (not sure if we'd want separate config options for each type of communication).  Users should be able to see who they have ignored, and undo those later (i.e. /unignore).  Mods in modmode and admins should be able to override /ignore at all times, to make sure important server info can be communicated.

**Comment by LadyCailin** [comment]
This probably shouldn't be implemented in CH, because the chat event is derpy in CH right now, though any plugin that implements this will obviously have to integrate with CH's clan chat.

**Comment by draykhar** [comment]
I'd like something with all of the features of this one:
http://dev.bukkit.org/server-mods/ignoreyou/

**Comment by FourDown** [comment]
Tested the plugin out, seems to be working fine.

Should be a simple drag and drop, no configuration needed.

**Comment by LadyCailin** [comment]
Check!
