### ISSUE TITLE
Remove requirement to wear boots/helmets to get player skull drop on S

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#88]
Planned feature for new S rev, proposed in user feedback and approved by S admins:
http://www.reddit.com/r/mcpublic/comments/1btgec/all_about_survival_rev21_part_2_upcoming_features/

Original version of this feature is described here:
http://www.reddit.com/r/mcpublic/comments/19tgy1/player_heads_now_drop_on_s/

We would like to make it such that neither player involved in a fight is required to be wearing a helmet or boots to get the skull drop - since both armor pieces break so easily in combat, especially with protection enchantments.

Both players would still need to be wearing iron/diamond chestplate and pants with Protection 3 or 4 on them.

**Comment by LadyCailin** [comment]
This is an easy fix. I just keep forgetting to do it while I'm on.

**Comment by LadyCailin** [comment]
Fixed :D
