### ISSUE TITLE
Add ability to give players rules and other info in-game in book form

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#89]
Planned feature for new S rev, proposed in user feedback and approved by S admins:
http://www.reddit.com/r/mcpublic/comments/1btgec/all_about_survival_rev21_part_2_upcoming_features/

Could be used on other servers (though P may be tricky, given the possibility of book trading with villagers).

Idea is to give players commands (such as /rule, /guide, etc.) to give them books in-game with the server rules, the guide to survival, or other important long-form information.

We may already be able to do this with existing plugins (e.g. CH).

**Comment by LadyCailin** [comment]
Yes, this is trivial with CH. I tested it out with the birthday book for cyotie, and it worked well.

**Comment by ludeman84** [comment]
I'll work on converting the rules and survival guide into book form.  Looks like Minecraft books are 19 characters per line and 13 lines per page, I'll try to get it into that format beforehand.

**Comment by ludeman84** [comment]
Have ported the S rules into the in-game book format:
http://paste.thezomg.com/9095/12340713/

I cleaned up and reorganized the rules a bit at nerd.nu/rules to be better suited for this format (removed rules in S section that were redundant in universal rules, rearranged, and added notes on recent gameplay changes to S that weren't on the rules page - no changes that actually modified gameplay / what's allowed).

**Comment by Tharine** [comment]
Think this one slipped past all of us a great deal, but it's definitely something we would still like to see on Survival. In the absence of this being created in CH, i'd love any recommendations (from anyone who see this) for a plugin that would allow us to perhaps give these books to players upon first spawn, in addition to whenever they run a specified command (with a cooldown period preferred, but not necessary).

**Comment by nopresnik** [comment]
This could easily be added to NerdSpawn.

**Comment by nopresnik** [comment]
Sorry if I seem as if I'm jumping in front of the techs.

[There is a plugin](http://dev.bukkit.org/bukkit-plugins/welcomebook/) out there that already does this. It seems to be easily configurable too! However, there are no cooldowns on the command to give you the book but you can easily add cooldowns with CH.

Installing another out-house plugin is probably the last resort the techs would want to do, but if they're too busy I can't see why not.

**Comment by ethancedrik** [comment]
Edited in depth discussion out as it does not belong here

**Comment by Tharine** [comment]
Just a reminder that the NerdBugs page is not intended for in-depth discussion of particular topics, it's about solving issues or implementing new features. If you have a suggestion for any particular relevant plugin for this, feel free to comment with it as I have asked, but if you're looking to discuss the pros and cons of such a thing at length, it's best left to other venues of communication.

**Comment by barneygale** [comment]
[FirstJoinPlus](http://dev.bukkit.org/bukkit-plugins/firstjoinplus/) will do this. I believe it's a pretty lightweight and well-written. Source is [here](https://github.com/chaseoes/FirstJoinPlus)

Could also be used to give spawn kits. Not sure if that's already a thing on nerd.

**Comment by LadyCailin** [comment]
``` php
bind(player_join, null, null, @e,
    if(@e['first_join']){
        @inv = array(array(type: 387))
        set_pinv(@inv)
        set_itemmeta(0, array(
            title: 'Da Rules',
            author: 'nerd.nu',
            pages: split('\n', read('path/to/book.txt'))
        ))
    }
)
```

Needs a tiny bit of cleanup, but this will work.

**Comment by LadyCailin** [comment]
This works on all the servers now, using the format that lude has. I just need all the rules to be given to me, and it's just a matter of updating the &lt;server&gt;/plugins/CommandHelper/firstjoinbook.txt files for each server.
