### ISSUE TITLE
Change div.Preview in forum CSS

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#92]
http://nerd.nu/forum/themes/mcpublic/design/custom.css?v=2.0.17.10 has both

```
div.Preview { background:#fff; }
```

and

```
div.Preview { background: #E3F4FF; }
```

and since the text is white, that makes previews really hard to see.  Consider removing both to allow the white text to be on the darker background.

**Comment by Deaygo** [comment]
fixed.
