### ISSUE TITLE
Enable /nv for mods in modmode on S and P

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#93]
Would make it much easier for mods to handle certain kinds of modreq's (e.g., placing flowing water in dark, confined grinder setups) and deal with possible xray investigating without having to place torches everywhere. 

Mods already had the ability to obtain and drink night vision potions to accomplish this; /nv would allow the use of keybinds to do so.  Note that /nv is already available for everyone on C.

Confirmed that potion effects won't carry over between modmode/non-modmode, so it can't be abused:
https://github.com/NerdNu/ModMode/pull/3

P and S admins have signed off on this change.

**Comment by draykhar** [comment]
Bugged LadyCailin about this one last night, she said it wouldn't be too difficult to do.

I'm for the implementation of this as soon as it's available.

**Comment by totemo** [comment]
Done.

**Comment by totemo** [comment]
Reopening to make /nv a toggle.

**Comment by totemo** [comment]
And done. Type /nv again to turn night vision off.
