### ISSUE TITLE
Player Heads Don't Drop in Certain Situations

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#94]
Player heads don't drop when all requirements are met (i.e. protection armor), if the victim is not directly killed by the killer (for example, the killer hits the victim with a fire sword and the victim dies from the fire damage).

BTW, killdb (or strikedeath?  I'm not familiar) still says "Victim was taken down by Killer wielding a diamond sword" correctly, even if it's fire from the diamond sword.  So that's recognizing the death OK.

**Comment by Tharine** [comment]
Commenting to query whether the issues with Fire Aspect swords was corrected, as well as to expand on the issue to say that wielding a named sword will negate the player head drop, even though all of the expected requirements are met. Is it possible at all to ignore what item is actually being used to land the final hit that decapitates the player?

**Comment by LadyCailin** [comment]
This needs to be fixed with a change to CH itself, so won't be a quick fix.

**Comment by LadyCailin** [comment]
Also fixed :D
