### ISSUE TITLE
Make locked chests the default on P.

### ISSUE THREAD

**Issue by totemo** [NerdNu/NerdBugs#96]
It's almost never the case that you want to place an unlocked chest on P.  Shouldn't the default action be the one that causes the least problems (least theft) and is used the most?

As I understand it, core.yml:

```
protections:
   autoRegister: true
```

**Comment by ludeman84** [comment]
This is more of a policy question than a tech task (as I think we've been able to do this technically for quite some time).  Can we start a thread about this idea on the forum or subreddit?

**Comment by totemo** [comment]
Yep.  I understand.  I'll close here and reopen on the forum.
