### ISSUE TITLE
Add CSS to subreddit to enable filtering by link flair

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#97]
Relevant forum thread:
http://nerd.nu/forum/index.php?p=/discussion/19396/sort-by-tag-on-the-subreddit#Item_4

Regardless of everyone's thoughts on the subreddit's nature and moderation in general [1], I can't see a downside to having this kind of filtering capability in place on the subreddit, if it is indeed feasible.

[1] http://www.reddit.com/r/mcpublic/comments/1cr3bc/ideas_for_improving_the_subreddit_forum_post/

**Comment by tompreuss** [comment]
Added to subreddit sidebar, see [changes here](http://www.reddit.com/r/mcpublic/wiki/config/sidebar?v=92f5819a-04b3-11e3-86bc-12313d1940ac&v2=e2ccc726-092e-11e3-a134-12313d1940ac).

Formatting might need a look at, but it's functional.

**Comment by LadyCailin** [comment]
This works, so I'm gonna close this bug now.
