### ISSUE TITLE
Fix ModReq unclaim/reopen message ambiguity

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#98]
Currently, [unclaim](https://github.com/NerdNu/ModReq/blob/master/src/nu/nerd/modreq/ModReq.java#L261) sends mods the message "%s%s is no longer handling request #%d" while [reopen](https://github.com/NerdNu/ModReq/blob/master/src/nu/nerd/modreq/ModReq.java#L364) sends "[ModReq] Request #%d is no longer claimed."

This is confusing as only closed reqs should be able to be reopened, so the "claimed" part of that message doesn't fit.  The unclaim command should be the one to reference something no longer being claimed.

**Comment by LadyCailin** [comment]
@tompreuss has volunteered to fix this bug ^_^

**Comment by FourDown** [comment]
This seems to have been dealt with, could a tech close this.

**Comment by tompreuss** [comment]
This has not been merged nor fixed yet.  The issue still occurs; I tested just now in game.  Please reopen.

**Comment by Tharine** [comment]
Does this issue still persist with our most recent setup (unsure if it's changed, but still) of ModReq?

And to avoid opening up a separate issue (or I can do, if best to, but it's tangentially related), running /reopen on a closed modreq will return an error message, but will still reopen the modreq just fine - it won't give you any of the above confirmation messages in doing so, however.

**Comment by tompreuss** [comment]
/unclaim shows the message I changed to, but /reopen acts as you describe @Tharine, because of a formatting error I made in my initial changes.

I've fixed and tested in the above pull request, so after that's merged and recompiled we should be good to go.

**Comment by LadyCailin** [comment]
Fixed, so closing.
