### ISSUE TITLE
Add domain re-directs to important S pages

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#99]
http://nerd.nu/sguide
maps to
http://redditpublic.com/wiki/Survival_Introduction

http://nerd.nu/smods
maps to
http://www.redditpublic.com/wiki/List_of_approved_client_mods

Would make it easier to reference these pages, and in particular to be able to include
them in-game in book form, per
https://github.com/NerdNu/NerdBugs/issues/89

**Comment by LadyCailin** [comment]
Done.
